- README.md
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/13
> 13: Update README with CDK version

- bin/config.sh
- config/7.0/obdemo-bank/ig/audit-schemas/ObConsentTopic.json
- config/7.0/obdemo-bank/ig/config/dev/config/config.json
- config/7.0/obdemo-bank/ig/config/prod/config/config.json
- config/7.0/obdemo-bank/ig/routes/routes-service/01-ob-rs-metadata.json
- config/7.0/obdemo-bank/ig/routes/routes-service/02-ob-as-metadata.json
- config/7.0/obdemo-bank/ig/routes/routes-service/03-ob-as-register.json
- config/7.0/obdemo-bank/ig/routes/routes-service/06-ob-idm-internal-handler.json
- config/7.0/obdemo-bank/ig/routes/routes-service/07-ob-account-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/08-ob-account-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/14-ob-token-endpoint.json
- config/7.0/obdemo-bank/ig/routes/routes-service/20-ob-rcs-api-getconsent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/21-ob-rcs-api-sendconsent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/99-ob-as.json
- config/7.0/obdemo-bank/ig/scripts/groovy/AuditConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessAccountConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessTPPRegistration.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ResponseHeaderFilter.groovy
- docker/7.0/ig/audit-schemas/ObConsentTopic.json
- kustomize/overlay/7.0/obdemo-bank/dev/configmap.yaml
Resolved: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/26
> 26: Enable auditing in IG

- config/7.0/obdemo-bank/ig/config/dev/config/config.json
- config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-payment-submission.json
- config/7.0/obdemo-bank/ig/scripts/groovy/CreateTPP.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessDetachedSig.groovy
- kustomize/overlay/7.0/obdemo-bank/dev/configmap.yaml
Resolves: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/7
> 7: check detached JWS signature header

- config/7.0/obdemo-bank/ig/config/dev/config/config.json
- docker/7.0/ig/Dockerfile
- kustomize/base/obdemo-rcs-ui/ingress.yaml
- kustomize/base/obdemo-rs/ingress.yaml
- kustomize/overlay/7.0/obdemo-bank/dev/configmap.yaml
Resolves: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/37
> 37: Update IG to 7.0.1 to remove requirement for AM cookie name config

- config/7.0/obdemo-bank/ig/routes/routes-service/30-internal-repo.json
- config/7.0/obdemo-bank/ig/scripts/groovy/RepoApiClient.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
Resolves: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/68
> 68: Update repo response for consents

- kustomize/overlay/7.0/obdemo-bank/dev/configmap.yaml
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAcceleratorToolkit/issues/70
> 70: Align postman collection and IG configuration

- config/7.0/obdemo-bank/ig/routes/routes-service/40-ob-jwkms.json
- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsProcessRequest.groovy
- kustomize/overlay/7.0/obdemo-bank/dev/ingress-patch.yaml
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAcceleratorToolkit/issues/64
> 64: Create signing service route

- config/7.0/obdemo-bank/ig/routes/routes-service/07-ob-account-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-payment-consent.json
Fix some invalid routes. secure baking uses `/open-banking`
> open-banking not openbanking

- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsIssueCert.groovy
- Response jwkms get certs changed from text to 'application/json' object
Issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests/issues/2
> 2: Functional tests fixes - Get certs

- config/7.0/obdemo-bank/ig/routes/routes-service/01-ob-rs-metadata.json
- config/7.0/obdemo-bank/ig/routes/routes-service/07-ob-account-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/08-ob-account-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/20-ob-rcs-api-getconsent.json
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessAccountConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessDetachedSig.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessPaymentConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/RCSGetConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/TranslateAccountsResource.groovy
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/67
> 67: Use consent prefixes according to type

- Makefile
- kustomize/base/ig/deployment.yaml
- kustomize/overlay/7.0/obdemo-bank/dev/kustomization.yaml
Default to the release repo for the init container.
Add image overrides for ig and the mock services.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/issues/38
> Image overrides

- kustomize/base/ig/deployment.yaml
- kustomize/overlay/7.0/obdemo-bank/christian/kustomization.yaml
use develop gcr repo for the initializer base
> use develop gcr repo for cloud env

- config/7.0/obdemo-bank/ig/routes/routes-service/01-ob-rs-metadata.json
- config/7.0/obdemo-bank/ig/routes/routes-service/08-ob-account-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/20-ob-rcs-api-getconsent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/21-ob-rcs-api-sendconsent.json
- kustomize/overlay/7.0/obdemo-bank/dev/configmap.yaml
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/80
> 80: IG config issues

- kustomize/overlay/7.0/obdemo-bank/nightly/configmap.yaml
- kustomize/overlay/7.0/obdemo-bank/nightly/kustomization.yaml
Create the nightly environment that uses the CDM rather than the internal CDK.
> create nightly environment

- config/7.0/obdemo-bank/ig/routes/routes-service/21-ob-rcs-api-sendconsent.json
- kustomize/overlay/7.0/obdemo-bank/dev/configmap.yaml
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/83
> 83: IG user object name incorrect for CDK

- Makefile
- config/7.0/obdemo-bank/ig/scripts/groovy/AddDetachedSig.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/CertificateRoleCheck.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/CreateApiClient.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsBuildSSA.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsIssueCert.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsSignClientClaims.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ParseCertificate.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessDetachedSig.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessRegistration.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/RCSGetConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/RCSSendConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/RepoApiClient.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/TranslateAccountsResource.groovy
- Support the 'unknown' value in the organisation identifier.
- Updated all script to add the error description in json format.
- Updated the make file to add a new target to build inly ig image.
Issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/issues/53
> 53: Registration process with ob certs

- config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/41-ob-jwkms-apiclient-issuecert.json
- config/7.0/obdemo-bank/ig/routes/routes-service/44-ob-jwkms-apiclient-get-tls-cert.json
- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsBuildSSA.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsGetTlsCert.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsIssueCert.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsSignClientClaims.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ParseCertificate.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/84
> 84: IG - standards based jwkms

- config/7.0/obdemo-bank/ig/routes/routes-service/30-internal-repo.json
- config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/85
> 85: Support PATCH of consents

- kustomize/overlay/7.0/obdemo-bank/bohocode/kustomization.yaml
- kustomize/overlay/7.0/obdemo-bank/christian-brindley/kustomization.yaml
- kustomize/overlay/7.0/obdemo-bank/jorgesanchezperez/kustomization.yaml
- kustomize/overlay/7.0/obdemo-bank/jterryfr/kustomization.yaml
apply the correct developer namespaces for IG.
> apply correct developer namespaces

- config/7.0/obdemo-bank/ig/routes/routes-service/40-ob-jwkms-rcs-signresponse.json
- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsProcessRCSClaims.groovy
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/87
> 87: RCS signing service in IG

- .github/workflows/pr.yml
- kustomize/overlay/7.0/obdemo-bank/bohocode/kustomization.yaml
- kustomize/overlay/7.0/obdemo-bank/christian-brindley/kustomization.yaml
- kustomize/overlay/7.0/obdemo-bank/jorgesanchezperez/kustomization.yaml
- kustomize/overlay/7.0/obdemo-bank/jterryfr/kustomization.yaml
Implement the github pr action to deploy changes to a develop environment.
issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/89
> add pr action

- .github/workflows/merge.yml
- .github/workflows/release.yml
- kustomize/overlay/7.0/obdemo-bank/dev/kustomization.yaml
Create github sha in the develop repo.
issue:  https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/89
> github sha on merge for develop repo

- kustomize/base/7.0/ingress/ingress.yaml
> Fix platform FQDN /rs endpoint

- kustomize/base/7.0/ingress/ingress.yaml
> ig /rs context endpoints

- kustomize/overlay/7.0/obdemo-bank/bohocode/configmap.yaml
- kustomize/overlay/7.0/obdemo-bank/christian-brindley/configmap.yaml
- kustomize/overlay/7.0/obdemo-bank/jorgesanchezperez/configmap.yaml
- kustomize/overlay/7.0/obdemo-bank/jterryfr/configmap.yaml
- kustomize/overlay/7.0/obdemo-bank/nightly/configmap.yaml
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/92
> 92: IG nightly missing RS_FQDN env variable

- config/7.0/obdemo-bank/ig/routes/routes-service/30-internal-repo.json
- config/7.0/obdemo-bank/ig/scripts/groovy/RepoUser.groovy
- Created new request on filter in the route internal-repo to manage users
Issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/issues/69
> 69: IG internal repo endpoint to manage users

- Makefile
- config/7.0/obdemo-bank/ig/config/dev/config/config.json
- config/7.0/obdemo-bank/ig/routes/routes-service/14-ob-token-endpoint.json
- config/7.0/obdemo-bank/ig/scripts/groovy/AddGatewayAuthorization.groovy
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/105
> 105: Enforce token endpoint access via IG

- .github/workflows/pr.yml
- kustomize/overlay/7.0/obdemo-bank/andra-racovita/configmap.yaml
- kustomize/overlay/7.0/obdemo-bank/andra-racovita/kustomization.yaml
- Added andra-racovita to environments
Issue: https://github.com/OpenBankingToolkit/openbanking-toolkit/issues/51
> 51: create new developer environment

- config/7.0/obdemo-bank/ig/routes/routes-service/01-ob-rs-metadata.json
- config/7.0/obdemo-bank/ig/routes/routes-service/08-ob-account-access.json
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessRs.groovy
For deployment on andra-racovita env
> Temporary RS discovery route

- .gitignore
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessAccountConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessPaymentConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/213
> 213: FIDC groovy scripts: Update Date time format

- config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-account-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-balances-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/13-ob-account-transactions-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/14-ob-account-beneficiaries-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/15-ob-account-direct-debits-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/16-ob-account-standing-orders-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/17-ob-account-products-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/18-ob-account-offers-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/19-ob-account-party-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/20-ob-account-scheduled-payments-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/21-ob-account-statements-access.json
Adding pattern to cover all API versions: v3.1(.[1-9])?
What will match examples:
v3.1
v3.1.1 ... v3.1.9
> Adding pattern to cover all patch versions

- config/7.0/obdemo-bank/ig/routes/routes-service/03-ob-as-register.json
- config/7.0/obdemo-bank/ig/scripts/groovy/CreateApiClient.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessRegistration.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/SSAVerifier.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/227
> 227: Modify the register Tpp route to support the delete method

- config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-access-multiple-routes.json
- config/7.0/obdemo-bank/ig/routes/routes-service/60-internal-repo.json
- config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
- changed the name of account access multiple routes
- Improved internal repo routes
- Improved repo consent groovy script
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/204
> 204: indentity platform client libraries

- config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-account-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/30-ob-payment-consent.json
- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessPaymentConsent.groovy
Issues:
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/137
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/138
Changes:
- changed the route's condition to accept all the supported versions
- added the implementation for retrieving a payment consent resource by id
> Domestic payment consent

- config/7.0/obdemo-bank/ig/scripts/groovy/ObResponseCheck.groovy
- Added response error content from OBErrorResponseException to error response
Issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests/issues/17
> 17: account statement file check response error

- config/7.0/obdemo-bank/ig/scripts/groovy/CreateApiClient.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ObResponseCheck.groovy
- Added log messages on responseCheck scripts
- Added apiClientOrg reference in apiClient object to link them
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/236
> 236: register client, create consent

- config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-access-multiple-routes.json
- config/7.0/obdemo-bank/ig/scripts/groovy/TranslateAccountsResource.groovy
- Added new userResourceOwner as attribute in the request
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/240
> 240: AISP evaluation script

- config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
- Added debtorAccount structure to patch the domestic payment consent
- Added condition to check orfan consents
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/230
> 230: domestic payment patch consent

- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessRs.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/253
> Add Domestic Payments Consents APIs in the RS Discovery

- kustomize/overlay/7.0/obdemo-bank/joycegilding-forgerock/configmap.yaml
- kustomize/overlay/7.0/obdemo-bank/joycegilding-forgerock/kustomization.yaml
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/252
> 252: Add new environment for Joyce Gilding

- config/7.0/obdemo-bank/ig/scripts/groovy/WellKnownFilter.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/255
I have changed the domain for the 'issuer' in WellKnownFilter.groovy from
`https://iam.dev.forgerock.financial:443/am/oauth2/realms/root/realms/alpha` to `https://obdemo.<env>.forgerock.financial:443/am/oauth2/realms/root/realms/alpha`
> Change the 'issuer' domain in WellKnownFilter.groovy

- config/7.0/obdemo-bank/ig/scripts/groovy/WellKnownFilter.groovy
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/260
> 260: Fix synax error in WellKnownFilter script

- config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsIssueCert.groovy
One of the thing I noticed when setting up a FAPI conformance test suite
config was that IG issues jwks without the alg defined correctly. This
PR fixes that for RSA keys.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/271
> 271: IG will issue jwks with alg defined

- config/7.0/obdemo-bank/ig/scripts/groovy/WellKnownFilter.groovy
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/260
> 260: Access authorize endpoint on iam.dev url

- config/7.0/obdemo-bank/ig/routes/routes-service/35-ob-scheduled-payment-consent.json
- config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
Functionality - implements the domestic scheduled payment consent route.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/278
> Creating domestic scheduled payment consent route

- kustomize/overlay/7.0/obdemo-bank/andra-racovita/configmap.yaml
- kustomize/overlay/7.0/obdemo-bank/christian-brindley/configmap.yaml
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/276
> Add developer IDENTITY_PLATFORM_FQDN to kustomise

- kustomize/overlay/7.0/obdemo-bank/joycegilding-forgerock/configmap.yaml
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/276
> Add IDENTITY_PLATFORM_FQDN to kustomize Joyce

- config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/340
> 340: Add Standing Order Consent case in the Repo Consent Script

- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessRs.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/349
> 349: Add Standing Order Consent APIs in RS Discovery

- config/7.0/obdemo-bank/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/41-ob-domestic-standing-order-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/42-ob-domestic-stnding-order-access.json
- config/7.0/obdemo-bank/ig/scripts/groovy/CheckFrequencyValue.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/GetResourceOwnerIdFromConsent.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/SaveIntentIdOnAttributesContext.groovy
**Issue**: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/324
**Description:** Adding routes to support domestic standing order submit and payment details APIs.
> Adding routes for submit and get details for standing orders

- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessRs.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/375
> 375: Add international payment consent APIs in RS discovery

- config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/361
> 361: Add International payment consent PATCH/GET case in the Repo Consent script

- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessRs.groovy
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/401
Description: Adding International Scheduled Payment endpoints to RS discovery.
> Update ProcessRs script to add international scheduled payment URLs

- config/7.0/obdemo-bank/ig/routes/routes-service/51-ob-international-schduled-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/409
Description: Adding the routes for submit international scheduled payment and access international payment and international payment-details
> Adding routes for international scheduled payments submit and access

- kustomize/overlay/7.0/obdemo-bank/bohocode/configmap.yaml
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/276
> 276: bohocode sbat use bohocode-cdk

- config/7.0/obdemo-bank/ig/routes/routes-service/31-ob-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/35-ob-scheduled-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/45-ob-international-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json
- config/7.0/obdemo-bank/ig/scripts/groovy/CalculateResponseElementsInRS.groovy
Issues:
- https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/427
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/433
> 427, 433: Add filter to send the consent request to RS to calculate response elements

- config/7.0/obdemo-bank/ig/scripts/groovy/ProcessDetachedSig.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/443
Updated the filter processing to use only async methods. The keys are retrieved using an async http call to the open banking directory jwks_uri, and once the response is received the correct key is identified. A promise with the key is created and when it's completed, the RSAKey is avaialble.
> 443: Replace nimbus.jose load method with an asynchronous http call for loading jwk_keys

- config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-account-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-access-multiple-routes.json
- config/7.0/obdemo-bank/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json
- config/7.0/obdemo-bank/ig/routes/routes-service/31-ob-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/32-ob-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/33-ob-domestic-payments-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/35-ob-scheduled-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/36-ob-scheduled-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/37-ob-scheduled-domestic-payments-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/41-ob-domestic-standing-order-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/42-ob-domestic-standing-order-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/45-ob-international-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/46-ob-international-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/47-ob-international-payment-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json
- config/7.0/obdemo-bank/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/51-ob-international-schduled-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json
- config/7.0/obdemo-bank/ig/routes/routes-service/54-ob-token-endpoint.json
- config/7.0/obdemo-bank/ig/scripts/groovy/ReturnInvalidCnfKeyError.groovy
- config/7.0/obdemo-bank/ig/scripts/groovy/ReturnTeapotError.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/238
Description: Implementing the certificate thumbrint validation for all the routes where it was missing. This is required for certificate bound access tokens.
Filter documentation:
https://backstage.forgerock.com/docs/ig/7.1/reference/CertificateThumbprintFilter.html
> Adding cnfKey verification for all required routes.

- config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-account-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-access-multiple-routes.json
- config/7.0/obdemo-bank/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json
- config/7.0/obdemo-bank/ig/routes/routes-service/31-ob-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/32-ob-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/33-ob-domestic-payments-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/35-ob-scheduled-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/36-ob-scheduled-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/37-ob-scheduled-domestic-payments-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/41-ob-domestic-standing-order-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/42-ob-domestic-standing-order-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/45-ob-international-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/46-ob-international-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/47-ob-international-payment-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json
- config/7.0/obdemo-bank/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json
- config/7.0/obdemo-bank/ig/routes/routes-service/51-ob-international-schduled-payment-submission.json
- config/7.0/obdemo-bank/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json
- config/7.0/obdemo-bank/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json
- config/7.0/obdemo-bank/ig/scripts/groovy/GrantTypeVerifier.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/337
Description: Adding grant type verification to all the required routes in order to prevent usage of wrong access tokens
> 337: Grant type verification

- config/7.1.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json
- Fix routes to not match funds confirmation condition
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/380
> 380: funds confirmation

- config/7.1.0/securebanking/ig/scripts/groovy/RepoConsent.groovy
To make it compatible with latests changes on RS until fixed 
https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/522
> Temporary fix

- config/7.1.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/461
Created the international standing order consent route
> 461: international-standing-order-consent

- config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/42-ob-domestic-standing-orders-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/57-ob-international-standing-orders-access.json
- config/7.1.0/securebanking/ig/scripts/groovy/ConsumeThePaymentIntent.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/GetResourceOwnerIdFromConsent.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/RepoConsent.groovy
- Renamed standing orders intent types
- Updated routes and groovy scripts
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/533
> 533: rename IDM standing orders intent objects

- kustomize/overlay/7.1.0/securebanking/dbadham-fr/configmap.yaml
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/276
> 276: Updating configmap for dbadham-fr environment to use the dbadham-fr iam instance

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRs.groovy
- Added File payment consent endpoints to RS discovery in `ProcessRs.groovy` script
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/548
> 548: Add file payment consent api to RS discovery

- config/7.1.0/securebanking/ig/scripts/groovy/RepoConsent.groovy
- Deleted specific cases to convertIDM responses for payments to use the default case and support all payment intent types
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/573
> 573: calculated elements file payments

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessPaymentConsent.groovy
- Deleted set the status in IG groovy script, this has been delegated to RS [PR-114](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/pull/114), the response will came with the proper status set.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/573
Comment: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/573#issuecomment-1277623393
> 573: calculate elements for file payments fix consent status

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessDetachedSig.groovy
- Refactor variable names to be more readable
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/587
> 587: Jws payload encoding fix

- config/7.1.0/securebanking/ig/routes/routes-service/59-ob-file-payment-consent-submission.json
- config/7.1.0/securebanking/ig/scripts/groovy/PatchFileConsent.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/ValidateFileConsent.groovy
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/588
Adding validation for file payment files in RS back office as per the issue description.
> Splitting consent route in two separate routes.

- kustomize/overlay/7.1.0/securebanking/bohocode/configmap.yaml
- kustomize/overlay/7.1.0/securebanking/dbadham-fr/configmap.yaml
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/570
> 570: Overriding RCS_UI_FQDN configuration for developers using their own namespace

- config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/61-ob-file-payment-access.json
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/555
Adding submit and access routes for file payments.
> File Payments - Create submit and access routes

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/619
> 619: Validated the "exp" (expiration) claim in the registration request JWT for DCR

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
Validate the "iss" (issuer) claim of the registration matches the software_id claim of the SSA
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/620
> 620: Validate the "iss" (issuer) claim of the registration

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/632
> 632: Validate DCR response_types in request is "code id_token"

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/621
> 621: Only add software_statement to successful AM responses

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRs.groovy
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/633
Description: Added Domestic VRP Payment consent APIs to RS discovery.
> 633: Add Domestic VRP Payment consent APIs to RS discovery

- kustomize/overlay/7.1.0/securebanking/bohocode/configmap.yaml
- kustomize/overlay/7.1.0/securebanking/christian-brindley/configmap.yaml
- kustomize/overlay/7.1.0/securebanking/dbadham-fr/configmap.yaml
- kustomize/overlay/7.1.0/securebanking/defaults/configmap.yaml
- kustomize/overlay/7.1.0/securebanking/dev/configmap.yaml
- kustomize/overlay/7.1.0/securebanking/frlaura-jianu/configmap.yaml
- kustomize/overlay/7.1.0/securebanking/jorgesanchezperez/configmap.yaml
- kustomize/overlay/7.1.0/securebanking/mariantiris/configmap.yaml
- kustomize/overlay/7.1.0/securebanking/nightly/configmap.yaml
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/667
> 667: Configure BASE_FQDN required by initializer to set cookie domain

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
DCR signature checking was added in: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/pull/220
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/624
> 624: Removing TODO comment which has now been implemented

- kustomize/overlay/7.1.0/securebanking/shaunharrisonfr/configmap.yaml
- kustomize/overlay/7.1.0/securebanking/shaunharrisonfr/kustomization.yaml
As part of 302 , I need to create an env for myself, new folder in the overlay is required
> 302 - Move kustomize out of gateway repo

- config/7.1.0/securebanking/ig/routes/routes-service/63-ob-domestic-vrp-funds-confirmation.json
- config/7.1.0/securebanking/ig/scripts/groovy/GetResourceOwnerIdFromConsent.groovy
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/634
Added route for domestic vrp funds confirmation and made required changes to add the correct amount on the backoffice request for VRPs.
> VRP funds confirmation

- .github/workflows/merge.yml
- .github/workflows/pr.yml
Fix for codefresh changes for allowing github actions to call pipelines
Issue : https://github.com/SecureApiGateway/SecureApiGateway/issues/706
> 706 Fix github actions calling codefresh pipelines

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
We need AM to be able to reach the OB jwks_uri. There was some 'odd' code in ProcessRegistration.groovy that re-wrote the jwks_uri, and we din't think it was necessary. However it is necessary, as it means that AM reaches out to a proxy route in IG that then goes and retrieves the jwks_uri. This is because AM doesn't have the OB certs in it's trust store.
I have put that code back
Issue: https://github.com/secureapigateway/secureapigateway/issues/733
> 733: Fix AM fails to reach OB jwks_uri

- secure-api-gateway-ig-extensions/README.md
- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectory.java
See page: https://github.com/SecureApiGateway/SecureApiGateway/wiki/IG-Extensions-Java-Module
Also fixing an issue in TrustedDirectory javadoc.
https://github.com/SecureApiGateway/SecureApiGateway/issues/735
> 735: Moving JWKS caching configuration documentation to the wiki

- config/7.1.0/securebanking/ig/scripts/groovy/RepoConsent.groovy
- Updated pach request body to fix the account id and update the debtor account data when the decision is submitted
Issue: https://github.com/secureapigateway/secureapigateway/issues/637
> 637: vrp payment account

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRs.groovy
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/772
Description: Changed the domestic vrp consents funds confirmation endpoint to match the other APIs.
> 772: Fixing domestic vrp consents funds confirmation endpoint

- config/7.1.0/securebanking/ig/scripts/groovy/CalculateResponseElementsInRS.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/ValidateDebtorAccountInRS.groovy
- Added encode for debtorAccount.Name
- Fix x-fapi-financial-id header
Issue: https://github.com/secureapigateway/secureapigateway/issues/731
> 731: debtor account as optional

- config/7.1.0/securebanking/ig/config/dev/config/config.json
- config/7.1.0/securebanking/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json
- config/7.1.0/securebanking/ig/routes/routes-service/31-ob-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/33-ob-domestic-payments-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/35-ob-scheduled-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/37-ob-scheduled-domestic-payments-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/42-ob-domestic-standing-orders-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/47-ob-international-payment-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json
- config/7.1.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json
- config/7.1.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/57-ob-international-standing-orders-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/59-ob-file-payment-consent-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/61-ob-file-payment-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/63-ob-domestic-vrp-funds-confirmation.json
- config/7.1.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/65-ob-domestic-vrps-access.json
Updating configuration to use new environment variable names as per PR: https://github.com/SecureApiGateway/sapig-openbanking-uk-developer-envs/pull/17
https://github.com/SecureApiGateway/SecureApiGateway/issues/751
> 751: Updating ASPSP OB signing key configuration

- config/7.1.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json
- config/7.1.0/securebanking/ig/scripts/groovy/VRPTypeVerifier.groovy
Issue: https://github.com/secureapigateway/secureapigateway/issues/736
Description: Added a new filter to the consent route to check if the VRPType is "Sweeping".
> 736: Allow only Sweeping VRPType

- config/7.1.0/securebanking/ig/scripts/groovy/VRPTypeVerifier.groovy
- Fix VRPTypeVerifier groovy script to process the check only when the method is post
Issue: https://github.com/secureapigateway/secureapigateway/issues/736
> 736: support vrp type sweeping only

- config/7.1.0/securebanking/ig/scripts/groovy/CalculateResponseElementsInRS.groovy
Issue: https://github.com/secureapigateway/secureapigateway/issues/715
Description: Changed x-fapi-financial-id header requirement from mandatory to optional.
> 715: X-fapi-financial-id header should be optional

- config/7.1.0/securebanking/ig/scripts/groovy/CalculateResponseElementsInRS.groovy
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/715
Description: Restored the x-fapi-financial-id header check in order for the functional tests to pass.
> 715: X-fapi-financial-id-header-check-back

- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/request/RegistrationRequestEntityValidatorFilter.java
- secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/request/RegistrationRequestEntityValidatorFilterTest.java
RegistrationRequestEntityValidator was running on all requests, but should only be running on POST and PUT
Issue: https://github.com/secureapigateway/secureapigateway/issues/811
> 811: Fix conformance-suite failures

- config/7.1.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/65-ob-domestic-vrps-access.json
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/807
- Removed status update to "Consumed" when a VRP is submitted
- Removed scripted policy validation call because it was unnecessary and would cause errors since the API is now called using DomesticVRPId instead of consentId. Code snippet below shows that no actual validations were performed on the GET case:
`                case "GET":
logger.message(script_name + "-[Payments]: GET request");
authorized = true
break;`
> Removing unnecessary validations for VRPs

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessAccountConsent.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/ProcessPaymentConsent.groovy
Verifying the consent's oauth2ClientId matches the access_token's oauth2ClientId when doing a GET.
A DELETE first does a GET to do the authorisation check.
https://github.com/SecureApiGateway/SecureApiGateway/issues/822
> 822: Adding TPP authorisation check to consent GET/DELETE methods

- config/7.1.0/securebanking/ig/routes/routes-service/31-ob-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/35-ob-scheduled-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/59-ob-file-payment-consent-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json
- config/7.1.0/securebanking/ig/scripts/groovy/CheckIdempotencyKey.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/PatchFileConsent.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/ProcessAccountConsent.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/ProcessPaymentConsent.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/ValidateFileConsent.groovy
- Added validation of idempotency requests for payment consents and file submission
Issue: https://github.com/secureapigateway/secureapigateway/issues/592
> 592: idempotency validation

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessPaymentConsent.groovy
- Added support to delete vrp consents in processPaymentConsent script Issue: https://github.com/secureapigateway/secureapigateway/issues/824
> 824: delete vrp consents

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/sigvalidation/RegistrationRequestJwtSignatureValidationService.java
- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/jws/RsaJwtSignatureValidator.java
Investigating failures in the conformance-dcr tests. Looks like the validation of the dynamic client registration jwt is failing.
Issue: https://github.com/secureapigateway/secureapigateway/issues/861
> Investigate failures in the conformance-dcr tests

- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientDecoder.java
- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/ApiClient.java
- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/ApiClientOrganisation.java
- secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/idm/ApiClientTest.java
- secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/jwks/DefaultApiClientJwkSetServiceTest.java
- secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/jwks/FetchApiClientJwksFilterTest.java
- secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/mtls/TokenEndpointTransportCertValidationFilterTest.java
- secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/FetchTrustedDirectoryFilterTest.java
- Adding deleted field to ApiClient
- Making ApiClient immutable
- Adding ApiClientBuilder
- Fixing tests to use the builder, added ApiClientTest which contains test data
https://github.com/SecureApiGateway/SecureApiGateway/issues/614
> 614: Adding deleted field to ApiClient

- config/7.1.0/securebanking/ig/scripts/groovy/GetResourceOwnerIdFromConsent.groovy
Logger line which is logging the amount for funds-confirmation flows throws an NPE when called for VRP payment.
Fixing the logging to work with all payment types.
Fixing error response blocks to return a Promise when inside a thenAsync block.
Fixing catch Exception block to return a response (it was building one but not returning it).
https://github.com/SecureApiGateway/SecureApiGateway/issues/873
> 873: Fixing NPE in GetResourceOwnerIdFromConsent amount logging

- config/7.1.0/securebanking/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json
- config/7.1.0/securebanking/ig/routes/routes-service/31-ob-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/33-ob-domestic-payments-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/35-ob-scheduled-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/37-ob-scheduled-domestic-payments-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/42-ob-domestic-standing-orders-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/47-ob-international-payment-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json
- config/7.1.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json
- config/7.1.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/57-ob-international-standing-orders-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/59-ob-file-payment-consent-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/61-ob-file-payment-access.json
- config/7.1.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/63-ob-domestic-vrp-funds-confirmation.json
- config/7.1.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/65-ob-domestic-vrps-access.json
https://github.com/SecureApiGateway/SecureApiGateway/issues/885
> 885: OB ASPSP Organsiation Id env var updated

- config/7.1.0/securebanking/ig/scripts/groovy/ProcessRs.groovy
When a single version is returned by the RS discovery, then the JsonValue in the ProcessRs is a Map rather than a List.
Fixing the script to always treat the value as a List.
https://github.com/SecureApiGateway/SecureApiGateway/issues/886
> 886: Fixing ProcessRs script to handle only a single API version being configured

- config/7.1.0/securebanking/ig/scripts/groovy/AuditConsent.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/CalculateResponseElementsInRS.groovy
- config/7.1.0/securebanking/ig/scripts/groovy/ValidateFileConsent.groovy
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/817
Removed x-fapi-financial-id header
> Removed x-fapi-financial-id header

- .github/dependabot.yml
Issue: https://github.com/secureapigateway/secureapigateway/issues/889
> 889: Enable dependabot version change PRs

- config/7.1.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy
- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientDecoder.java
- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/ApiClient.java
- secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientDecoderTest.java
ApiClient.roles has been updated from string => array of strings
See PR: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-fidc-initializer/pull/173
https://github.com/SecureApiGateway/SecureApiGateway/issues/865
> 865: IDM ApiClient schema change

- .github/workflows/merge.yml
- pom.xml
Fix maven help to retrieve the version as condition to set the server id
- Updated merge master workflow
- Updated pom file maven plugins
Issue: https://github.com/secureapigateway/secureapigateway/issues/812
> 812: release actions maven fixes

- .github/workflows/merge.yml
- .github/workflows/release-publish-java-and-docker.yml
- .github/workflows/release-publish-java.yml
- .github/workflows/release.yml
- Makefile
- Added steps to override the maven setting after build the java artifact to make ready it to deploy on community repo
- Updated merge master
- Renamed and updated release java workflow to `release publish java and docker`:
-  We need to build the docker image in the same workflow where java library is built to have the latest built version of IG extensions library in the config/lib folder when the docker image is built. 
Issue: https://github.com/secureapigateway/secureapigateway/issues/812
> 812: release action fix maven protected settings

- .github/workflows/release-publish-java-and-docker.yml
- .github/workflows/release.yml
- Updated step names to be more clear
- updated job names to be more clear
Issue: https://github.com/secureapigateway/secureapigateway/issues/812
> 812: release action clean up

- pom.xml
- secure-api-gateway-ig-extensions/pom.xml
Issue: https://github.com/secureapigateway/secureapigateway/issues/929
> 929: Update versions as suggested by dependabot

- pom.xml
Issue: https://github.com/secureapigateway/secureapigateway/issues/929
> 929: Update version of nimbus-jose

- pom.xml
- secure-api-gateway-ig-extensions/pom.xml
- Updated pom files artifact version to 1.0.0-SNAPSHOT to be ready to build the release 1.0.0
Issue: https://github.com/secureapigateway/secureapigateway/issues/927
> 927: update development version to 1.0.0

- config/7.1.0/securebanking/ig/scripts/groovy/RepoUser.groovy
- Repo user groovy script modified to support queryFilter to retrieve psu user by username
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1005
> 1005: test user data

- config/7.1.0/securebanking/ig/scripts/groovy/GetResourceOwnerIdFromConsent.groovy
- Fix GetResourceOwnerIdFromConsent groovy script to validate properly the consent status when is the request is for funds-confirmation
- Clean up and improvement to the script
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1027
> 1027: fix GetResourceOwnerIdFromConsent groovy script to validate properly the consent status

- config/7.1.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json
- config/7.1.0/securebanking/ig/routes/routes-service/63-ob-domestic-vrp-funds-confirmation.json
- config/7.1.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json
- config/7.1.0/securebanking/ig/routes/routes-service/65-ob-domestic-vrps-access.json
Removing filters which impl IDM consent logic from VRP routes.
Removing AM policy script call from VRP routes, this is now implemented in the RS.
Adding x-api-client-id header to all VRP routes.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1050
> 1050: Updating VRP Consent routes to reverse proxy RS

- config/7.1.0/securebanking/ig/routes/routes-service/66-ob-funds-confirmation-consent.json
- Added route 66 to support funds confirmation consent API requests
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/600
> 600: Route for funds confirmation consent API

- config/7.2.0/securebanking/ig/routes/routes-service/66-ob-funds-confirmation-consent.json
- config/7.2.0/securebanking/ig/routes/routes-service/67-ob-funds-confirmation-availability.json
- Added route 67 for Funds confirmations
- Fix description of api client role check script filter
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/606
> 606: Funds confirmation availability route

- config/7.2.0/securebanking/ig/routes/routes-service/68-ob-aggregated-polling.json
- config/7.2.0/securebanking/ig/scripts/groovy/VerifyAccessTokenScopes.groovy
- Added route 68-ob-aggregated-polling
- Added groovy script VerifyAccessTokenScopes to verify the access token scope required for accessing the API, the access token scope must have at last one allowed scope configured in the script filter `Token Scopes Verifier`
- Spec Ref: https://openbankinguk.github.io/read-write-api-site3/v3.1.11/profiles/aggregated-polling-api-profile.html#security
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1001
> 1001: aggregated polling API route

- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/FAPIAdvancedDCRValidationFilter.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1114
> 1114: Fixing typo in FAPIAdvancedDCRValidationFilter javadoc

- pom.xml
- secure-api-gateway-ig-extensions/pom.xml
- Updated development version to 2.1.0-SNAPSHOT
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1148
> 1148 prepare release 2.1.0

- config/7.3.0/securebanking/ig/routes/routes-service/72-ob-jwkms-apiclient-getssa.json
Fix for PR: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/436
https://github.com/SecureApiGateway/SecureApiGateway/issues/898
> 898: Fixing AddCertificateToAttributesContextFilter config for route: 72-ob-jwkms-apiclient-getssa.json

- docker/7.3.0/ig/Dockerfile
Preparing for if we need to switch back
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1153
> 1153: Change IG base version to 7.2.0

- docker/7.3.0/ig/Dockerfile
https://github.com/SecureApiGateway/SecureApiGateway/issues/1154
> 1154: Upgrading IG to version 2023.4.0

- secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/TokenEndpointMetricsContextSupplier.java
- secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/metrics/TokenEndpointMetricsContextSupplierTest.java
Parsing the scope String from the OAuth2.0 token endpoint (/access_token) request, converting the whitespace separated String value into a List<String> to make querying easier.
In BigQuery, an array is used for this value which supports querying.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1151
> 1151: Adding scope data to the TokenEndpointMetricsContext

- pom.xml
- secure-api-gateway-ig-extensions/pom.xml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1182
> Prepare eminem release 2.2.0

- .github/workflows/pr.yml
Change stage names & add in condition for running deploy if not dependabot
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1220
> 1220: Dependabot CI/CD

- .github/workflows/release-prepare.yml
https://github.com/SecureApiGateway/SecureApiGateway/issues/1139
> 1139: Updating Java version to 17

- .github/workflows/release-publish-java-and-docker.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/987
> 987: Missed file while fixing pipeline issue

- .github/workflows/codeql.yml
Scanning will be done when a PR is merged to master and on a once weekly schedule.
https://github.com/SecureApiGateway/SecureApiGateway/issues/900
> 900: Configuring CodeQL scanning

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- .github/workflows/release-prepare.yml
- .github/workflows/release-publish-java-and-docker.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1257
> 1257: Update java action and distribution

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- .github/workflows/release-prepare.yml
- .github/workflows/release-publish-java-and-docker.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1264
> 1264: Update actions that have deprecations

- pom.xml
https://github.com/SecureApiGateway/SecureApiGateway/issues/1272
> 1272: Update parent to 2.3.1 release version

- config/7.3.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy
Returning 401 Unauthorized when updating an ApiClient fails due to the client being deleted.
Returning 404 Not Found when updating an ApiClient fails due to the client not being found in IDM.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1278
> 1278: Fixing error code when updating ApiClient

- .github/workflows/merge.yml
Run the make command to build a dev IG docker image and push to artifact registry
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1328
> 1328: Change Individual Environments to use a dev IG Image

- config/7.3.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json
The filter has been renamed in core extensions module, updating route config to use the new name.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1117
> 1117: Update FapiAdvancedDCRValidationFilter name in route config

- config/7.3.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json
The filter has been renamed in core extension module.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1117
> 1117: Update RegistrationRequestBuilderFilter name in route config

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- .github/workflows/slackNotification.yml
- Makefile
Amend PR Slack Notify & Merge workflow to use steps in CI Repo
Standardise workflows in the process of doing this
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1389
> 1389: Use CI Repo for standardised steps in github workflows

- pom.xml
Update Parent and Core for version 3.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1404
> 1404: Create and Release SAPIG Core and OB

- Makefile
- secure-api-gateway-ob-uk-docker/Dockerfile
Upgrade openig to 2024.9.0
Allow additional parameters be passed in docker and maven from command line
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1540
> 1540: Upgrade OpenIG to 2024.9.0

- config/7.3.0/securebanking/ig/config/dev/config/config.json
- pom.xml
Bump `parent` and `core` version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1602
> 1602: Build and Deploy SAPIG 4.0.0

- pom.xml
Update Parent to 4.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1625
> 1625: SAPIG Release 4.0.3 - Further OB V4 Support

- config/7.3.0/securebanking/ig/config/dev/config/config.json
- config/7.3.0/securebanking/ig/config/prod/config/config.json
Fix SAPIG OB UK prod config.json following move to core IG components (openig-fapi)
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1620
Follow on from PR #574 to address changes in prod (config.json only)
> 1620: Fix SAPIG OB UK prod config.json following move to core IG components

- .github/workflows/pr-helm.yml
- Makefile
- _infra/helm/secure-api-gateway-ob-uk/Chart.yaml
- _infra/helm/secure-api-gateway-ob-uk/readme.md
- _infra/helm/secure-api-gateway-ob-uk/templates/configmap.yaml
- _infra/helm/secure-api-gateway-ob-uk/templates/deployment.yaml
- _infra/helm/secure-api-gateway-ob-uk/templates/ingress.yaml
- _infra/helm/secure-api-gateway-ob-uk/templates/secret.yaml
- _infra/helm/secure-api-gateway-ob-uk/templates/service.yaml
- _infra/helm/secure-api-gateway-ob-uk/values.yaml
- _infra/kustomize/base/configmap.yaml
- config/7.3.0/securebanking/ig/config/dev/config/config.json
- config/7.3.0/securebanking/ig/config/prod/config/config.json
Add in helm packages
Changes to standardise TTD FQDN
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1679
> 1679: Changes for IG using Helm

- .github/workflows/merge.yml
- .github/workflows/pr-helm.yml
- .github/workflows/pr.yml
- .github/workflows/rebase.yml
- .github/workflows/slackNotification.yml
- _infra/helm/secure-api-gateway-fapi-pep-rs-ob/Chart.yaml
- _infra/helm/secure-api-gateway-fapi-pep-rs-ob/templates/deployment.yaml
- _infra/helm/secure-api-gateway-fapi-pep-rs-ob/templates/ingress.yaml
- _infra/helm/secure-api-gateway-fapi-pep-rs-ob/templates/service.yaml
- _infra/helm/secure-api-gateway-fapi-pep-rs-ob/values.yaml
- Add in helm pr workflow
- Adjust Helm Chart for test release
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1682
> 1682: Use new Helm files to deploy to Relenv

- _infra/helm/secure-api-gateway-fapi-pep-rs-ob/Chart.yaml
- pom.xml
Bump parent and core version to 5.0.0
Bump helm chart version to 5.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1703
> 1703: Create SAPIG 5.0.0

- config/7.3.0/securebanking/ig/scripts/groovy/ProcessDetachedSig.groovy
Fixing groovy compilation errors after some IG refactoring
> Fixing groovy compilation errors

- config/7.3.0/securebanking/ig/scripts/groovy/AddDetachedSig.groovy
- config/7.3.0/securebanking/ig/scripts/groovy/RepoApiClient.groovy
- config/7.3.0/securebanking/ig/scripts/groovy/RepoUser.groovy
- Rework of RepoApiClient to operate in an async way as this route/script is frequently called.
> OPENIG-9667 Investigation into OB FT failures
