docker/obdemo-rcs-api/Dockerfile, docker/obdemo-rs/Dockerfile
- Moved `docker/obdemo-rcs-api/psd-2-rsc-sevice-0.0.2-SNAPSHOT.war` to **securebanking** bucket
- Moved `docker/obdemo-rs/ForgerockREST-0.0.1-SNAPSHOT.jar` to **securebanking** bucket
- Modified dockerfiles of `obdemo-rcs-api` and `obdemo-rs` to add large files from **securebanking** bucket
- Deleted large files `docker/obdemo-rcs-api/psd-2-rsc-sevice-0.0.2-SNAPSHOT.war` and `docker/obdemo-rs/ForgerockREST-0.0.1-SNAPSHOT.jar`
Resolves #5
=> 5: github warning large files

bin/config.sh
- Change the conversion of `IG mode` to uppercase using the `tr` command instead of the syntax `^^`
- The script convert the `IG_mode` selected by the user or the default value to uppercase because the json descriptor where is set that value require an uppercase value.
- Solves [Issue 10](https://github.com/SecureBankingAcceleratorToolkit/securebanking-openbanking-demo/issues/10)
=> 10: bad substitution error in config script

kustomize/overlay/7.0/obdemo-bank/dev/deployment-patch.yaml
Rather than use internal kube dns to ping idm for a health check. use the `IAM_FQDN` instead. This should fix the init problem for local development.
=> ping the fqdn

kustomize/overlay/7.0/obdemo-bank/dev/deployment-patch.yaml
Change the container name to `iam-init`
default the initializer to look for the release repository.
prefix the curl request with `https://`
https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/issues/10
https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/issues/25
=> apply fixes

config/7.0/obdemo-bank/ig/routes/routes-service/01-ob-rs-metadata.json, config/7.0/obdemo-bank/ig/routes/routes-service/08-ob-account-access.json, config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-payment-submission.json, kustomize/overlay/7.0/obdemo-bank/dev/configmap.yaml
Add a new environment variables `RS_URL` and `RCS_URL` that references the internal kube dns address of their respective services.
Reference this address in the ig routes for rs.
Change the discovery endpoint to redirect to the real [rs simulator](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/blob/86f4cd340a3a0c5ad45d44d407ac7ee554cc32ff/securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/discovery/DiscoveryController.java#L69)
Apply similar change from `openbanking` to open-banking
=> Connect rs

kustomize/overlay/7.0/obdemo-bank/dev/configmap.yaml
Call a `null-issuer` cert-manager issuer which does not exist in the deployment. by default cert-manager should not be used and a certificate should be brought down from a secret store which is supplied by the namespace setup chart.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/issues/30
pr: https://github.com/ForgeCloud/sbat-infra/pull/59
=> call an invalid cert-manager issuer

config/7.0/obdemo-bank/ig/config/dev/config/admin.json, config/7.0/obdemo-bank/ig/scripts/groovy/BasicAuthResourceServerFilter.groovy, kustomize/README.md, kustomize/base/ig/secret.yaml, kustomize/overlay/7.0/obdemo-bank/dev/kustomization.yaml, kustomize/overlay/7.0/obdemo-bank/dev/secrets-prometheus-patch.yaml
Create a filter and groovy script for implementing basic protection for the metrics endpoint.
The script is basic as follows the [guide](https://backstage.forgerock.com/docs/ig/7/maintenance-guide/proc-monitor-plat-protect.html) exactly.
This is deployed to the dev environment which doesnt need strict protection on the metrics endpoint so the username/password can be exposed for the purpose of this example.
Added an annotation to the secret to allow for secret replication to the `prometheus` namespace within the dev cluster.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/issues/34
=> protect the metrics endpoint

.github/workflows/merge.yml, Makefile, kustomize/overlay/7.0/obdemo-bank/cloud/configmap.yaml, kustomize/overlay/7.0/obdemo-bank/cloud/deployment-patch.yaml, kustomize/overlay/7.0/obdemo-bank/cloud/ingress-patch.yaml, kustomize/overlay/7.0/obdemo-bank/cloud/kustomization.yaml, kustomize/overlay/7.0/obdemo-bank/cloud/secrets-prometheus-patch.yaml
Create a new overlay for cloud deployments that do not require skaffold and do not deploy the mock services for rs and rcs.
Apply github actions and build and push a container with every merge to master.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/issues/38
=> Cloud deployment

kustomize/overlay/7.0/obdemo-bank/dev/configmap.yaml
IG does not have its own namespace. We do not need the config to point to a specific namespace
=> remove unneeded config

kustomize/overlay/7.0/obdemo-bank/christian/configmap.yaml, kustomize/overlay/7.0/obdemo-bank/christian/kustomization.yaml, kustomize/overlay/7.0/obdemo-bank/jamie/configmap.yaml, kustomize/overlay/7.0/obdemo-bank/jamie/kustomization.yaml, kustomize/overlay/7.0/obdemo-bank/john/configmap.yaml, kustomize/overlay/7.0/obdemo-bank/john/kustomization.yaml, kustomize/overlay/7.0/obdemo-bank/jorge/configmap.yaml, kustomize/overlay/7.0/obdemo-bank/jorge/kustomization.yaml
Add developer overlays for their own ephemeral kubernetes namespaces.
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/21
=> add developer overlays

config/7.0/obdemo-bank/ig/scripts/groovy/JwkmsIssueCert.groovy
- Changed the field `pemCert` to `x5c` in the response json to align with the standard
- Script: `JwkmIssueCert.groovy`
Issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests/issues/2
=> Change the field pemCert to x5c

kustomize/base/ig/deployment.yaml
Routes were not appearing in IG deployments. This was because the latest
images was not ALWAYS being pulled from gcr.
Issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/issues/48
=> 48: Make deployment alway pull latest image

config/7.0/obdemo-bank/ig/routes/routes-service/70-ob-jwkms-rcs-signresponse.json
- Changed the jwt payload signresponse argument Value `routeArgJwtIssuer` from forgerock-rcs to secure-open-banking-rcs
=> Fix iss jwtIssuer

config/7.0/obdemo-bank/ig/scripts/groovy/WellKnownFilter.groovy
This is needed for conformance and also because am is not usable without the access token that is held by IG, so going direct to ig doesn't work.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/260
=> 260: Fix all am urls in oauth2 well known to use IG urls

config/7.0/obdemo-bank/ig/routes/routes-service/02-ob-as-metadata.json, config/7.0/obdemo-bank/ig/routes/routes-service/54-ob-token-endpoint.json, config/7.0/obdemo-bank/ig/routes/routes-service/99-ob-as.json
Working through the audience issue with @christian-brindley. We might need to rely on x-forwarded header values in AM, to match aud values in client credential jwts... so this pr sets them to be obdemo.<env>.forgerock.financial, which is what Api Clients including the FAPI compliance suite will set their audience values to.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/260
=> 260: Add valid ig forwarded-for values for AS routes

config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-account-consent.json, kustomize/base/7.0/ingress/ingress.yaml, kustomize/base/obdemo-bank/application.yaml
Later versions of kubernetes have done away with the old schema type for Ingress
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/299
=> 299: Update the ingress manifest

config/7.0/obdemo-bank/ig/routes/routes-service/32-ob-payment-submission.json, config/7.0/obdemo-bank/ig/routes/routes-service/33-ob-domestic-payments-access.json, config/7.0/obdemo-bank/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.0/obdemo-bank/ig/scripts/groovy/GetResourceOwnerIdFromConsent.groovy, config/7.0/obdemo-bank/ig/scripts/groovy/ModifyPaymentIntentResponse.groovy, config/7.0/obdemo-bank/ig/scripts/groovy/ProcessRs.groovy, config/7.0/obdemo-bank/ig/scripts/groovy/TranslatePaymentResource.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/312
```
* "GetDomesticScheduledPayment": "https://obdemo.<env>.forgerock.financial/rs/open-banking/v3.1.1/pisp/domestic-scheduled-payments/{DomesticScheduledPaymentId}",
* "CreateDomesticScheduledPayment": "https://obdemo.<env>.forgerock.financial/rs/open-banking/v3.1.1/pisp/domestic-scheduled-payments"
```
=> Fix the x-ob-account-id header for Domestic Scheduled Payments

config/7.0/obdemo-bank/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json, config/7.0/obdemo-bank/ig/scripts/groovy/GetResourceOwnerIdFromConsent.groovy, config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
- Updated `domesticStandingOrderPaymentIntent` to `domesticStandingOrderIntent`
- updated `internationalStandingOrderPaymentIntent` to `internationalStandingOrderIntent`
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/354
=> 354: update domestic standing order intent name

.gitignore, config/7.0/obdemo-bank/ig/scripts/groovy/ProcessDetachedSig.groovy
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/306
Description: There's an issue with the nimbus jose library used to retrieve the jwk sets which in combination which IG causes thread to hang if for some reason the connection is not closed by nimbus JWKSet.load method.
=> 306 ig pods restart randomly

config/7.0/obdemo-bank/ig/config/dev/config/logback.xml, config/7.0/obdemo-bank/ig/config/prod/config/logback.xml
Changing logging pattern to log messages on a single line, adding a timestamp to the start of the line and logging full exception stacktraces (for dev env only, to aid debugging)
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/506
=> 506: Improving logging pattern

config/7.0/obdemo-bank/ig/config/dev/config/logback.xml, config/7.0/obdemo-bank/ig/config/prod/config/logback.xml
Removing ANSI color codes from IG logging, this makes logs more readable when viewed in tools which do not process the ANSI codes. This produces a log output which is similar to our other java apps.
Output can be viewed here: https://argo.dev.forgerock.financial/applications/ig-securebanking-dbadham-fr?resource=&node=%2FPod%2Fdbadham-fr%2Fig-6dfc9ddc98-d68x5%2F0&tab=logs
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/506
=> 506: Removing ANSI color codes from logging

config/7.0/obdemo-bank/ig/routes/routes-service/32-ob-payment-submission.json, config/7.0/obdemo-bank/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.0/obdemo-bank/ig/routes/routes-service/41-ob-domestic-standing-order-submission.json, config/7.0/obdemo-bank/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.0/obdemo-bank/ig/routes/routes-service/51-ob-international-schduled-payment-submission.json, config/7.0/obdemo-bank/ig/scripts/groovy/ConsumeThePaymentIntent.groovy, config/7.0/obdemo-bank/ig/scripts/groovy/GetResourceOwnerIdFromConsent.groovy, config/7.0/obdemo-bank/ig/scripts/groovy/ProcessDetachedSig.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/505
- Created the ConsumeThePaymentIntent groovy script to change the payment intent status to **Consumed** after the payment was submitted
- If the intent status is Consumed, the funds confirmation request should return a BAD REQUEST error
From the [OB documentation](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-payment-consents.html#get-international-payment-consents-consentid-funds-confirmation):
An ASPSP can only respond to a funds confirmation request if the payment consent (international payment, international scheduled payment) resource has an Authorised status. If the status is not Authorised, an ASPSP must respond with a 400 (Bad …
=> 505: After a payment is submitted the consent status must be changed to Consumed

.github/workflows/merge.yml
https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/pull/162 was merged previously, this has broken the dev env as it has produced a docker image that is missing the jwks ig extension module.
Updating the github action on merge to do the maven build.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/503
=> 503: Updating merge.yml action to build the maven modules prior to building the docker image

config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-account-consent.json, config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json, config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-access-multiple-routes.json, config/7.0/obdemo-bank/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json, config/7.0/obdemo-bank/ig/routes/routes-service/31-ob-payment-consent.json, config/7.0/obdemo-bank/ig/routes/routes-service/32-ob-payment-submission.json, config/7.0/obdemo-bank/ig/routes/routes-service/33-ob-domestic-payments-access.json, config/7.0/obdemo-bank/ig/routes/routes-service/35-ob-scheduled-payment-consent.json, config/7.0/obdemo-bank/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.0/obdemo-bank/ig/routes/routes-service/37-ob-scheduled-domestic-payments-access.json, config/7.0/obdemo-bank/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json, config/7.0/obdemo-bank/ig/routes/routes-service/41-ob-domestic-standing-order-submission.json, config/7.0/obdemo-bank/ig/routes/routes-service/42-ob-domestic-standing-order-access.json, config/7.0/obdemo-bank/ig/routes/routes-service/45-ob-international-payment-consent.json, config/7.0/obdemo-bank/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.0/obdemo-bank/ig/routes/routes-service/47-ob-international-payment-access.json, config/7.0/obdemo-bank/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json, config/7.0/obdemo-bank/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json, config/7.0/obdemo-bank/ig/routes/routes-service/51-ob-international-schduled-payment-submission.json, config/7.0/obdemo-bank/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json, config/7.0/obdemo-bank/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json, config/7.0/obdemo-bank/ig/scripts/groovy/ProcessAccountConsent.groovy, config/7.0/obdemo-bank/ig/scripts/groovy/ProcessDetachedSig.groovy, config/7.0/obdemo-bank/ig/scripts/groovy/ProcessPaymentConsent.groovy, config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy, config/7.0/obdemo-bank/ig/scripts/groovy/ReturnPolicyValidationError.groovy
Issues: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/510
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/516
Adding a failure handler to better highlight errors return by the PolicyEnforcementFilter for the cases when the policy validation fails.
Adding fixes for functional tests, thumbprint validation, and grant validation.
=> Adding failure handlers for policy validation error

config/7.1.0/securebanking/ig/scripts/groovy/CalculateResponseElementsInRS.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/509
Modifying the path to the calculate elements API to have version in path and dynamic context for each consent type.
=> 509: Update API expected body from String to OB data model object

config/7.1.0/securebanking/ig/scripts/groovy/ProcessRs.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/462
Adding consent URL's in RS discovery response for International Standing Orders.
=> 462: RS Discovery consent URL's for Internation Standing Orders

config/7.1.0/securebanking/ig/scripts/groovy/RepoConsent.groovy
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/463
Description: Added international standing order consent PATCH/GET case in the repo consent script to store the debtorAccount in the intent object.
=> 463: Adding international standing order consent PATCH/GET case in the repo consent script

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/config/prod/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/03-ob-as-register.json, config/7.1.0/securebanking/ig/scripts/groovy/ParseCertificate.groovy, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
Verify transport cert used during DCR (dynamic client registration) is mapped to the TPP's software statement
- TLS cert is found in the HTTP header ssl-client-cert in PEM format (set by nginx)
- software_jwks_endpoint property in software statement is used to locate the TPP's JWKSet
- ProcessRegistration script now fetches the JWKSet and checks to see if a TLS cert exists by looking for a JWK with an x5c value which matches the TLS cert used to submit the DCR request
- OBIE spec notes that the x5c will only contain a single item (the client's cert) without any chain, and nginx will only send the cert on without the chain.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/524
=> 524: Verify transport cert used during DCR 

config/7.1.0/securebanking/ig/scripts/groovy/GetResourceOwnerIdFromConsent.groovy
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/532
Description: Fixed managed object name constant in GetResourceOwnerIdFromConsent.groovy. Wrong - internationalStandingOrdersIntent. Correct - internationalStandingOrderIntent
=> 532: Corrected managed object name

config/7.1.0/securebanking/ig/routes/routes-service/10-ob-account-consent.json, config/7.1.0/securebanking/ig/scripts/groovy/ProcessAccountConsent.groovy, config/7.1.0/securebanking/ig/scripts/groovy/RepoConsent.groovy
- Updating ProcessAccountConsent.groovy to create IDM objects with the new structure
- Updating RepoConsent.groovy to query/patch the new structure, note that this script is shared by all intent types so logic has been added to only use the new structure for Account Access Intents. Eventually all intent types will be updated to the new structure
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/535
=> 535: Updating to use new Account Access Intent IDM object structure

config/7.1.0/securebanking/ig/scripts/groovy/RepoConsent.groovy
Updating RepoConsent to return "OBIntentObject" in response payloads rather than "data" or "Data"
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/522
=> 522: Updating RepoConsent to return OBIntentObject in response payloads 

config/7.1.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json
- Fix `routeArgIntentType` for File Payments consent to calculate elements for `PFC_` intent type
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/573
=> 573: Calculate elements implementation fix entitytype arg to PFC_

config/7.1.0/securebanking/ig/scripts/groovy/ProcessAccountConsent.groovy
Currently HTTP 200 is returned when deleting an account access consent, with the consent json being sent in the response body.
Fixing this as per the OB spec to return HTTP 204 No Content.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/537
=> 537: Fixing a bug in the delete account consent flow

securebanking-openbanking-uk-gateway-jwks/src/test/java/com/forgerock/securebanking/uk/gateway/jwks/cache/caffeine/CaffeineCacheTest.java
The test works when run locally, but we have noticed failures when run via a GitHub action. The failures appear to be due to the test taking longer than expected to add the items to the cache, which means that some have been evicted before expected.
Fixing by increasing the expiryDuration and doing a sanity test that the cache has items (rather than checking for an exact number)
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/576
=> 576: Improving test CaffeineCacheTest.shouldEvictEntriesBasedOnTime

config/7.1.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json, config/7.1.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
- Operating on an existing registration requires the uri to be rewritten to conform to the AM api (passing client_id as a query param rather than in the path)
- Using a ConditionalFilter to only add the IG Access token for POST requests (registering a new client), the GET/PUT/DELETE  calls needs to supply their own access token (which was returned in the registration_access_token field of the DCR response)
- Renaming route to 03-ob-dcr-register-tpp.json
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/597
=> 597: Fixing GET/PUT/DELETE routes for DCR

config/7.1.0/securebanking/ig/scripts/groovy/SSAVerifier.groovy
Fixing a bug where the next.handle is called from the request handling thread and also from the jwksResponse async block. This results in 2 calls being made to AM, which causes 2 clients to be created.
The updated logic is as follows:
- For requests to create/update a DCR we need to validate the SSA, which needs to make an async request to the JWKS (and then verify the sig), if this is successful then the request can continue to the next handler.
- For get/delete, nothing needs to be done in the SSAVerifier, the request is passed directly to the next handler
=> 618 Fixing SSAVerifier to only call next.handle once 

config/7.1.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy
CreateApiClient filter runs after the response from the ReverseProxyHandler that talks to AM. The apiClient must only be deleted if the AM response is successful i.e. AM delete the OAuth2 client
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/597
=> 597: Fixing IDM apiClient delete logic to only run if the AM delete was successful

config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
If the subject_type is missing then we need to set the subject_type to "pairwise" otherwise it will be set by default to "public"
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/623
=> 623: Handles missing subject_type

config/7.1.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
For GET requests, the ssa needs to be looked up from IDM.
Fixed a bug which meant that the IDM apiClient.ssa field was set to null. This was due to the trying to set the field based on the response from AM. We do not pass the ssa (software_statement) field to AM, therefore it is not in the response.
For POST & PUT requests, the ssa from the request is added to the response from AM.
DELETE returns no content.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/621
=> 621: Fixing DCR API to return software_statement in POST/PUT/GET responses

.gitignore, kustomize/overlay/7.1.0/securebanking/andra-racovita/configmap.yaml, kustomize/overlay/7.1.0/securebanking/andra-racovita/kustomization.yaml, kustomize/overlay/7.1.0/securebanking/christian-brindley/configmap.yaml, kustomize/overlay/7.1.0/securebanking/dev/configmap.yaml, kustomize/overlay/7.1.0/securebanking/frlaura-jianu/configmap.yaml, kustomize/overlay/7.1.0/securebanking/jorgesanchezperez/configmap.yaml, kustomize/overlay/7.1.0/securebanking/mariantiris/configmap.yaml, kustomize/overlay/7.1.0/securebanking/nightly/configmap.yaml
Change kustomize overlays to make each developer's sbat env point at their own CDK. This kustomize overlay is used to create a config map that contains the settings by the SBAT elements to communicate with a CDK. 
Nightly will point at the FIdC instance.
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/570
=> 570: Configure sbat namespaces to use correct FR Platforms

config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
Bug was introduced as part of refactoring to support software_statement in DCR response.
Fixing other variables incorrectly named jwtSet to jwkSet for consistency
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/621
=> 621: Fixing jwkSet variable name

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/config/prod/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy, config/7.1.0/securebanking/ig/scripts/groovy/SSAVerifier.groovy, securebanking-openbanking-uk-gateway-jwks/pom.xml, securebanking-openbanking-uk-gateway-jwks/src/main/java/com/forgerock/securebanking/uk/gateway/jws/JwtSignatureValidator.java, securebanking-openbanking-uk-gateway-jwks/src/main/java/com/forgerock/securebanking/uk/gateway/jws/RsaJwtSignatureValidator.java, securebanking-openbanking-uk-gateway-jwks/src/test/java/com/forgerock/securebanking/uk/gateway/jws/RsaJwtSignatureValidatorTest.java
Adding RsaJwtSignatureValidator which validates that a SignedJwt's signature can be verified against a signing key in a supplied JWKSet
Calling the new validator from ProcessRegistration filter to verify the signature of the DCR JWT. 
Refactoring the SSAVerifier filter to use the new validator, instead of its validation written in groovy, to validate the signature of the SSA.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/624
=> 624: Validating the DCR JWT signature

config/7.1.0/securebanking/ig/routes/routes-service/11-ob-account-access.json, config/7.1.0/securebanking/ig/routes/routes-service/12-ob-account-access-multiple-routes.json, config/7.1.0/securebanking/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/31-ob-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/33-ob-domestic-payments-access.json, config/7.1.0/securebanking/ig/routes/routes-service/35-ob-scheduled-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/37-ob-scheduled-domestic-payments-access.json, config/7.1.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/42-ob-domestic-standing-orders-access.json, config/7.1.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/47-ob-international-payment-access.json, config/7.1.0/securebanking/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json, config/7.1.0/securebanking/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/57-ob-international-standing-orders-access.json, config/7.1.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/59-ob-file-payment-consent-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/61-ob-file-payment-access.json
The AM config has been updated to issue tokens for the IG domain i.e. https://obdemo.dbadham-fr.forgerock.financial/am/oauth2/realms/root/realms/alpha 
See work done previously for: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/255
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/670
=> 670: Updating accessTokenResolver config to verify issuer matches IG domain

config/7.1.0/securebanking/ig/config/dev/config/config.json
Configuring the x-ob-url header required by the RS backends for all routes.
NOTE: contexts.router.originalUri could also be used, but it would need editing to replace the http:// with https:// (as nginx is terminating TLS in front of IG)
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/673
=> 673: Configuring x-ob-url for all routes

config/7.1.0/securebanking/ig/routes/routes-service/54-ob-token-endpoint.json
The ObResponseCheck filter should only be used for formatting error responses for calls to the Open Banking API.
Calls to the token endpoint should produce errors as per the OAuth2/OIDC specs (which is what AM produces).
Removing the ObResponseCheck filter from the token endpoint route so that the AM error response is propagated back to the caller.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/674
=> 674: Removing ObResponseCheck from AM token endpoint route

config/7.1.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json
FAPI changes were made in parallel with VRP route being developed, the route contains old configuration which needs to be updated so that the issuer is checking the IG domain.
Fixing to use the correct reverse proxy handler, consent route is reverse proxying IDM in this instance: SBATReverseProxyHandlerIdentityPlatform
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/254
=> 254: Fixing vrp consent route to use the correct issuer

config/7.1.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json, config/7.1.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy, config/7.1.0/securebanking/ig/scripts/groovy/SSAVerifier.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/securebanking/gateway/DcrErrorResponseFactory.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/securebanking/gateway/dcr/ErrorResponseFactory.groovy
Improving DCR error handling by creating an error factory which can be used to consistently report DCR errors. The error format for bad client requests adheres to the spec: https://www.rfc-editor.org/rfc/rfc7591#section-3.2.2
[ErrorResponseFactory](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/6b5b3f7e1c138d22463736d5b0850432362b98b4/config/7.1.0/securebanking/ig/scripts/groovy/com/securebanking/gateway/dcr/ErrorResponseFactory.groovy) is a groovy class which is imported into the ProcessRegistration and SSAVerifier filter scripts which make up the core DCR logic. 
This pattern can be applied to reuse logic between groovy filters. To do this place groovy classes under scripts/groovy dir in a standard groovy package structure. You can then import …
=> 641: Improve DCR error handling

config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
Handling InvalidJwtExceptions raised by JwtReconstruction for DCR registration request JWT and software_statement claim jwt.
This means that a HTTP 400 error is returned with an error msg, rather than a HTTP 500
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/641
=> 641: Handling InvalidJwtExceptions raised by JwtReconstruction

config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/securebanking/gateway/dcr/ErrorResponseFactory.groovy
The redirect_uris must match or be a subset of the software_statement.software_redirect_uris
If no redirect_uris are present in the registration request, then all the software_statement.software_redirect_uris will be used
The ob spec also requires that redirect_uris use https and do not have localhost as the host
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/655
=> 655: Validating DCR redirect_uris

config/7.1.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy
Changes to CreateApiClient POST handling:
- Properly chained Promises using thenAsync when making http calls in response handling i.e. calling IDM as part of handling the AM response
- Fixed error handling
- Return Response objects or Promises wrapping Response objects as appropriate
- Unexpected errors from IDM will bubble up as HTTP 500 errors
- Changed order of calls to create the apiClientOrg first (if it does not already exist), then creating the apiClient
- Using a PUT with header "If-None-Match: *" to prevent existing apiClientOrg objects being overwritten
Useful CREST documentation:
https://backstage.forgerock.com/docs/idm/7.2/crest/crest-create.html
https://backstage.forgerock.com/docs/idm/7.2/crest/crest-status-codes.html
Issue: …
=> 683: Refactoring CreateApiClient to use Promise API correctly

config/7.1.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy
PUT is used to update an existing DCR.
The CreateApiClient filter needs to update the IDM apiClient object for the DCR being updated. This logic is done on the response path (same as for POST), so that we only do the update if AM accepted the DCR update.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/656
=> 656: Support PUT in CreateApiClient filter

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/config/prod/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/02-ob-as-metadata.json, config/7.1.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json, config/7.1.0/securebanking/ig/scripts/groovy/ASWellKnownFilter.groovy, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
- Adding ASWellKnownFilter to modify the AM well-known response to restrict the token_endpoint_auth_methods_supported values
- Adding oauth2.tokenEndpointAuthMethodsSupported IG config to control the above
- Configuring private_key_jwt as the only supported value. FAPI also allows tls_client_auth but this is not supported by SAPI-G yet.
- Validating DCR request against the supported auth methods
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/690
=> 690: Restrict token_endpoint_auth_methods_supported

.github/workflows/pr.yml
The branch from which the deploy is being made now relates to the branch of sapig-openbanking-uk-developer-envs, not the IG repo branch, so we should not override this
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/302
=> 302: Fix deployment of IG on push of PR

config/7.1.0/securebanking/ig/routes/routes-service/04-ob-as-authorize.json, config/7.1.0/securebanking/ig/scripts/groovy/FapiCompliantAuthorizeRequestFilter.groovy, config/7.1.0/securebanking/ig/scripts/groovy/GrantTypeVerifier.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/jwt/JwtClaimNames.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/oauth/OAuthErrorResponseFactory.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/ContentTypeNegotiator.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/HttpHeaderNames.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/HttpMediaTypes.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/HttpRequestParameterNames.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/content/ContentTypeFormatter.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/content/ContentTypeFormatterFactory.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/content/ContentTypeFormatterFormUrlEncoded.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/content/ContentTypeFormatterHtml.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/content/ContentTypeFormatterJson.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/content/ContentTypeFormatterText.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/rest/content/ContentTypeNegotiator.groovy
Fixes for failures when running the fapi1-advanced-final conformance suite tests.
There are some issues with the validation of our request object
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/676
=> 676: Ensure authorize request jwt conforms to FAPI spec

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/99-ob-as.json
Route 99 is the "pass through" route for AM access which does not have a more specific route. This includes accessing the XUI.
Adding new handler SBATReverseProxyHandlerIdentityPlatformNoCapture and using it in route 99 in order to stop capturing these messages in the logs. Access to the XUI includes all calls to fetch html/css/js resources and if capturing is enabled this floods the logs.
Also fixing a bug with the SBATReverseProxyHandlerIdentityPlatform and SBATReverseProxyHandlerRs handlers which were logging captures twice, this is due to them have capturing enabled and the underlying ReverseProxyHandler also having capturing enabled.
If we find that there are other flows which are hitting route 99, and if we deem them important enough to have message capturing, then we can add a …
=> 678: Disabling message capture for IG route 99

config/7.1.0/securebanking/ig/config/dev/config/config.json
When reverse proxying AM, the /authorize call is returning header list size > 8k (the default max size). This causes an exception to be thrown in IG, due to it being unable to decode the HTTP frame.
Example exception:
```
Caused by: io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException: Header size exceeded max allowed size (8192)
at io.netty.handler.codec.http2.Http2Exception.headerListSizeError(Http2Exception.java:194)
at io.netty.handler.codec.http2.Http2CodecUtil.headerListSizeExceeded(Http2CodecUtil.java:233)
at io.netty.handler.codec.http2.HpackDecoder$Http2HeadersSink.finish(HpackDecoder.java:545)
at io.netty.handler.codec.http2.HpackDecoder.decode(HpackDecoder.java:132)
at io.netty.handler.codec.http2.DefaultHttp2HeadersDecoder.decodeHeaders(DefaultHttp2HeadersDecoder …
```
=> 304: Increase vertx maxHeaderSize and maxHeaderListSize properties to 16k

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy, config/7.1.0/securebanking/ig/scripts/groovy/SSAVerifier.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/forgerock/sapi/gateway/jwt/JwtUtils.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/SecureApiGatewayClassAliasResolver.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectory.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryOpenBankingTest.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectorySecureApiGateway.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryService.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryServiceHeaplet.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryServiceStatic.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryOpenBankingTestTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectorySecureApiGatewayTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryServiceStaticTest.java
The config for a trusted directory should be obtained via a service
**Note:** For now, while developing this config, it is hard coded in specific classes. Once the config has been developed so that it holds all the information needed about a TrustedDirectory, this information can be held in a store. Probably it will be stored in IDM as a managed object. Other alternatives could be to store it in Mongo, or in a config file etc. 
Issue: https://github.com/secureapigateway/secureapigateway/issues/728
=> 728: Create heap service to provide trusted directory

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/31-ob-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/35-ob-scheduled-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/59-ob-file-payment-consent-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/SecureApiGatewayClassAliasResolver.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/FetchApiClientFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientDecoder.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/FetchTrustedDirectoryFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/FetchApiClientFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientDecoderTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/FAPIAdvancedDCRValidationFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/FetchTrustedDirectoryFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/util/TestHandlers.java
This filter will add the TrustedDirectory for this ApiClient to the attributes context. NOTE: FetchTrustedDirectoryFilter should be installed in a filter chain after the FetchApiClientFilter filter, as the ApiClient data is required to determine the TrustedDirectory.
Added filter chain: FetchApiClientAndTrustedDirectoryDataChain which can be used to fetch the ApiClient and then the TrustedDirectory. Updating existing usages of the FetchApiClientFilter in routes to use the new chain.
https://github.com/SecureApiGateway/SecureApiGateway/issues/729
=> 729: Adding FetchTrustedDirectoryFilter

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/jwks/RestJwkSetService.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/jwks/cache/CachingJwkSetService.java
The findJwkByKeyId function is now public, reusing it in the CachingJwkSetService and it can also be used when we have a JWKS in the attributes context and we want to lookup a JWK from it.
https://github.com/SecureApiGateway/SecureApiGateway/issues/729
=> 729: Cleanup CachingJwkSetService by reusing the findJwkByKeyId helper function in RestJwkSetService

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/31-ob-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/35-ob-scheduled-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/59-ob-file-payment-consent-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json, config/7.1.0/securebanking/ig/scripts/groovy/ProcessDetachedSig.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/SecureApiGatewayClassAliasResolver.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/jwks/FetchApiClientJwksFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/jwks/JwkSetService.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/jwks/RestJwkSetService.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/jwks/cache/CachingJwkSetService.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/jwks/FetchApiClientJwksFilterTest.java
FetchApiClientJwksFilter uses the ApiClient and TrustedDirectory objects from the context to lookup and set the apiClientJwkSet attribute. This attribute contains the JWKSet object which holds the keys that the ApiClient has registered with the TrustedDirectory.
Updated ProcessDetachedSig filter to use the apiClientJwkSet attribute to find the key to use when validating the signature.
https://github.com/SecureApiGateway/SecureApiGateway/issues/729
=> 729: Adding FetchApiClientJwksFilter

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json, config/7.1.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy, config/7.1.0/securebanking/ig/scripts/groovy/SSAVerifier.groovy, config/7.1.0/securebanking/ig/scripts/groovy/com/securebanking/gateway/dcr/ErrorResponseFactory.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectory.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryOpenBankingTest.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectorySecureApiGateway.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryOpenBankingTestTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectorySecureApiGatewayTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryServiceStaticTest.java
Based on the description of how Dynamic Client Registration should work [here](https://github.com/SecureApiGateway/SecureApiGateway/wiki/About-Dynamic-Client-Registration) we need to ensure that ProcessRegistration.groovy:
Does not depend upon details within the certificate. This is brittle - we should not require the presented cert to be in eIDAS form.
Relies upon using the TrustedDirectoriesService to determine the directory from which a software_statement was issued and use the trusted directory JWKS or jwks_uri to validate the certificate rather than trying to inspect the certificate.
Performs the necessary checks defined in the OB Dynamic Client Registration specification
Issue: https://github.com/secureapigateway/secureapigateway/issues/733
=> 773: process registration should not rely on certificate

config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
The new util method JwtUtils.getSignedJwtFromString will have handled and logged the exception, no additional logging is required in this if block.
https://github.com/SecureApiGateway/SecureApiGateway/issues/733
=> 733: Remove log line which contains reference to an exception which does not exist in this scope.

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/FAPIAdvancedDCRValidationFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/FAPIAdvancedDCRValidationFilterTest.java
The token_endpoint_auth_signing_alg field is optional in the DCR request (depending on the token_endpoint_auth_method). Changing validation logic for signing fields to skip fields if they are not present in the request.
The job of the FAPIAdvancedDCRValidationFilter is to reject requests that are not FAPI compliant, it is not expected to implement the DCR logic. Therefore, checking if fields are set correctly as per the OAuth2 DCR spec is a job for the filter that implements this logic.
https://github.com/SecureApiGateway/SecureApiGateway/issues/740
=> 740: Fixing signing algorithm validation bug in FAPIAdvancedDCRValidationFilter

config/7.1.0/securebanking/ig/scripts/groovy/SSAVerifier.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectory.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryOpenBankingTest.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectorySecureApiGateway.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryServiceHeaplet.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryServiceStatic.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/jwks/FetchApiClientJwksFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/FetchTrustedDirectoryFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectorySecureApiGatewayTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryServiceStaticTest.java
This will ensure configuration errors are caught earlier.
Issue: https://github.com/secureapigateway/secureapigateway/issues/769
=> 769: Make TrustedDirectory return URL for directoryJwksUri

config/7.1.0/securebanking/ig/config/dev/config/config.json, docker/7.1.0/ig/Dockerfile, docker/7.1.0/ig/bin/import-pem-certs.sh, docker/README.md
Adding import-pem-certs.sh script to import PEM certs into the truststore, this script is added to the docker image.
https://github.com/SecureApiGateway/SecureApiGateway/issues/764
=> 764: Allowing ig truststore to be configured by importing PEM files

config/7.1.0/securebanking/ig/routes/routes-service/71-ob-jwkms-apiclient-issuecert.json, config/7.1.0/securebanking/ig/routes/routes-service/72-ob-jwkms-apiclient-getssa.json
Removing unused arg: routeArgEncryptionKey for script: JwkmsIssueCert.groovy, env var CA_KEK can also be removed from deployment config.
Heap obj: SystemAndEnvSecretStore-SSA is not referenced anywhere, this is the sole reference to the IG_SSA_SECRET env var which can also be removed from deployment config.
https://github.com/SecureApiGateway/SecureApiGateway/issues/764
=> 764: Removing unused environment variables from config

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/75-ob-jwkms-test-directory-jwks.json, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectorySecureApiGatewayTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryServiceStaticTest.java
Also updating the route's path to replace apiclient with testdirectory for the same reason.
https://github.com/SecureApiGateway/SecureApiGateway/issues/765
=> 765: Renaming route to make it clear that the JWKS returned belongs to the Test Directory and not the ApiClient

config/7.1.0/securebanking/ig/routes/routes-service/31-ob-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/35-ob-scheduled-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json, config/7.1.0/securebanking/ig/scripts/groovy/CalculateResponseElementsInRS.groovy, config/7.1.0/securebanking/ig/scripts/groovy/ValidateDebtorAccountInRS.groovy
- Added new scriptable filter for payment initiation routes to validate the debtor account when is provided
- Added new groovy script to call RS to retrieve the account by identifiers provided in the debtor account consent 
> The consent will be rejected with an error description when the debtor account does not exist
```json
{
"Code": "400",
"Id": "5412c3719b1535a0b93d9fef9322b95d",
"Message": "[Status: 400 Bad Request]",
"Errors": {
"ErrorCode": "UK.OBIE.Field.Invalid",
"Message": "Bad request [Invalid debtor account, the debtor account provided in the consent does not exist]"
}
}
```
Issue: https://github.com/secureapigateway/secureapigateway/issues/731
=> 731: optional debtor account validation

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/70-ob-jwkms-rcs-signresponse.json, config/7.1.0/securebanking/ig/routes/routes-service/72-ob-jwkms-apiclient-getssa.json, config/7.1.0/securebanking/ig/routes/routes-service/75-ob-jwkms-test-directory-jwks.json
The configuration was reusing config for the ca keystore, changed to use its own set of env vars.
Made the alias name configurable.
Renamed the store to TestDirectorySigningKeyStore.
Related PR: https://github.com/SecureApiGateway/sapig-openbanking-uk-developer-envs/pull/15
https://github.com/SecureApiGateway/SecureApiGateway/issues/765
=> 765: Cleaning up configuration of the Test Directory Signing Key Store

config/7.1.0/securebanking/ig/routes/routes-service/70-ob-jwkms-rcs-signresponse.json, config/7.1.0/securebanking/ig/routes/routes-service/72-ob-jwkms-apiclient-getssa.json
Heap object: SystemAndEnvSecretStore-RCS is not referenced. It looks like an old Secret Store that may have been used to implement HMAC JWT signing. The env var IG_RCS_SECRET can now be removed.
Also removing SecretKeyPropertyFormat-RCS and SecretKeyPropertyFormat-SSA objects as they are not referenced anywhere.
https://github.com/SecureApiGateway/SecureApiGateway/issues/783
=> 783: Removing unused heap objects from jwkms routes

docker/7.1.0/ig/Dockerfile
The forgerock user is created by the base image and is intended to be used to run the application.
Switching to root to run some privileged commands only.
Reordering the Dockerfile to place things that change more frequently near the end to make better use of layer caching.
https://github.com/SecureApiGateway/SecureApiGateway/issues/776
=> 776: Updating Dockerfile to run IG as forgerock user

config/7.1.0/securebanking/ig/routes/routes-service/83-rcs-api.json, config/7.1.0/securebanking/ig/scripts/groovy/RcsApiConsentRequestJwtResolver.groovy
The new route does authentication and authorisation checks on calls made to the RCS API. These changes are similar to those made for the RCS UI in PR: https://github.com/SecureApiGateway/securebanking-openbanking-uk-gateway/pull/301
A new filter has been added to the route: RcsApiConsentRequestJwtResolver which resolves the consent_request JWT for the ConsentRequestJwtValidationFilter to validate it. The JWT is found in different locations depending on which API call is being made.
To do the authorisation checks we are validating the consent_request JWT. This means the RCS backend can trust that the JWT has had its signature verified.
https://github.com/SecureApiGateway/SecureApiGateway/issues/805
=> 805: Adding route 83-rcs-api.json which protects the RCS API

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/common/exceptions/DCRException.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/sigvalidation/RegistrationRequestJwtSignatureValidationService.java
The DCR tests are failing because the field name error_code should be just 'error'.
Issue: https://github.com/secureapigateway/secureapigateway/issues/811
=> 811: Use correct DCR error response field names

config/7.1.0/securebanking/ig/routes/routes-service/01-ob-rs-metadata.json, config/7.1.0/securebanking/ig/routes/routes-service/02-ob-as-metadata.json, config/7.1.0/securebanking/ig/scripts/groovy/ASWellKnownFilter.groovy
Applying multiple gateway changes for the MTLS epic in this PR
**838: Updating AS .well-known response to use the mtls hostname for endpoints which require OB mtls**
Added mtlsEndpoints configuration to the route, currently the registration_endpoint and token_endpoint are configured for mtls.
Updated to filter to update the .well-known response to replace the IG hostname with the MTLS hostname for the configured endpoints
**842: Updating RS metadata route to use the mtls hostname**
All calls to RS require MTLS.
Changing the X-Forwarded-Host to use the MTLS host so that RS generates the links correctly.
https://github.com/SecureApiGateway/SecureApiGateway/issues/838
https://github.com/SecureApiGateway/SecureApiGateway/issues/842
https://github.com/SecureApiGateway/SecureApiGateway/issues/78 …
=> 782: Changes to support MTLS subdomain

config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/common/jwt/ClaimsSetFacade.java
We would need to fix the routes before turning this off and should have a further discussion about the merits of using TLS certificate validation vs certificate bound access tokens
Issue: https://github.com/secureapigateway/secureapigateway/issues/733
=> 733: Reintroduce certificate bound access tokens

config/7.1.0/securebanking/ig/scripts/groovy/ProcessDetachedSig.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientDecoder.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientService.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientDecoderTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientServiceTest.java
http://openbanking.org.uk/iss header claim is validated to check it matches "{{org-id}}/{{software-statement-id}}"
To do this we need to get the ApiClient data, as the ProcessDetachedSig filter runs after FetchApiClientFilter then this data is available in the attributes context.
Fixing bug in IDM query which was not retrieiving the fields within the apiClientOrg object.
Fixing bug in ProcessDetachedSig which caused validation errors to be ignored as the isJwsSignatureValid was returning a Promise wrapping a boolean instead of a boolean.
https://github.com/SecureApiGateway/SecureApiGateway/issues/691
=> 691: Fixing ProcessDetachedSig header claim: http://openbanking.org.uk/iss validation

config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/common/jwt/ClaimsSetFacade.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/RegistrationRequest.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/SoftwareStatement.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectory.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryOpenBankingTest.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectorySecureApiGateway.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/common/jwt/ClaimsSetFacadeTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/models/RegistrationRequestBuilderTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/models/RegistrationRequestFactory.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/models/RegistrationRequestTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/models/SoftwareStatementBuilderTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/request/RegistrationRequestEntityValidatorFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryTest.java
As a part of issue #733 I removed the redirect_uri checks from ProcessRegistration, believing that these checks were done in the FAPIAdvancedDCRValidationFilter. However, that is not the case, so re-instating this check in the ProcessRegistration script for now
Issue: https://github.com/secureapigateway/secureapigateway/issues/864
=> 864: Perform redirect_uri checks in ProcessRegistration

config/7.1.0/securebanking/ig/config/dev/config/logback.xml, config/7.1.0/securebanking/ig/config/prod/config/logback.xml, config/7.1.0/securebanking/ig/routes/routes-service/10-ob-account-consent.json, config/7.1.0/securebanking/ig/scripts/groovy/FapiTransactionIdFilter.groovy
Using MDC enables contextual information to be added to all log lines.
- Updating FapiTransactionIdFilter to add x-fapi-interaction-id value to MDC
- The filter the old MDC context value back once it has finished with a request
- This idiom comes from the ig filter: MdcRouteIdFilter
- Changing logging config to use JsonLayout which will log the MDC values
- This layout is better suited to cloud logging
- Google Log Explorer will now be able to display multi-line log messages
- Adding filter chain: SBATFapiInteractionFilterChain to route: 10-ob-account-consent.json, this chain is at the start of all routes to ensure fapi interaction id and forgerock transaction id are set correctly.
https://github.com/SecureApiGateway/SecureApiGateway/issues/671
=> 671: Adding x-fapi-interaction-id value to MDC

config/7.1.0/securebanking/ig/config/dev/config/config.json, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/SecureApiGatewayClassAliasResolver.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/common/exception/SapiLogAttachedExceptionFilterHeaplet.java
LogAttachedExceptionFilter does not have a heaplet, in order to control where it gets installed in a filter chain then a heaplet is required to be able to create it in config.
Creating SapiLogAttachedExceptionFilter as an alias of LogAttachedExceptionFilter. Using an alias will prevent issues occurring should IG add their own Heaplet for the filter in future.
Installing the filter after FapiTransactionIdFilter. This means that when it catches an unhandled exception, it will log the x-fapi-interaction-id. Without this change a randomly generated transactionId is logged which makes it impossible to find when searching by x-fapi-interaction-id.
The existing LogAttachedExceptionFilter that IG installs by default will handle any unexpected exceptions that occur between the 2 filters. …
=> 684: Creating SapiLogAttachedExceptionFilter alias for LogAttachedExceptionFilter

config/7.1.0/securebanking/ig/routes/routes-service/11-ob-account-access.json, config/7.1.0/securebanking/ig/routes/routes-service/12-ob-account-access-multiple-routes.json, config/7.1.0/securebanking/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/33-ob-domestic-payments-access.json, config/7.1.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/37-ob-scheduled-domestic-payments-access.json, config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/42-ob-domestic-standing-orders-access.json, config/7.1.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/47-ob-international-payment-access.json, config/7.1.0/securebanking/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json, config/7.1.0/securebanking/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/57-ob-international-standing-orders-access.json, config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/61-ob-file-payment-access.json, config/7.1.0/securebanking/ig/routes/routes-service/63-ob-domestic-vrp-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/65-ob-domestic-vrps-access.json
Using MTLS_FQDN environment variable to set X-Forwarded-Host header for OB routes; this value is `mtls.sapig.dev.forgerock.financial` for the dev namespace.
https://github.com/SecureApiGateway/SecureApiGateway/issues/875
=> 875: Setting OB route header: X-Forwarded-Host using config

config/7.1.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientDecoder.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientService.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/ApiClient.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/idm/ApiClientTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientDecoderTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/idm/IdmApiClientServiceTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/models/SoftwareStatementTestFactory.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/sigvalidation/DCRTestHelpers.java
Roles are needed for access decisions, and the roles in the SSA ultimately limit the roles that a client can request and the apis that a client can access. Each API request needs to know which roles were in the Software Statement and limit access accordingly.
Issue: https://github.com/secureapigateway/secureapigateway/issues/865
=> 865: Store SSA roles in the ApiClient object

Makefile, config/7.1.0/securebanking/ig/config/prod/config/admin.json, config/7.1.0/securebanking/ig/config/prod/config/config.json
Bringing the prod config.json up to date, as it has not been used for a long time. Applying all changes made to the dev config.json to this file.
Key differences between dev and prod config:
- Prod routes are immutable
- Will not be reloaded from disk
- IG Studio is disabled
- Test Trusted Directory disabled
- JWKS caching time is 30mins in prod vs 24hrs in dev
Adding env variable to the Makefile, this allows dev or prod docker images to be built.
By default dev images are built, set env=prod for production images.
https://github.com/SecureApiGateway/SecureApiGateway/issues/826
=> 826: Updating IG prod config

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/config/prod/config/config.json
IDMClientHandler is wrapping the ForgeRockClientHandler. Both Handlers have capturing turn on, this means that messages are captured and logged twice. Disabling capturing on the IDMClientHandler.
https://github.com/SecureApiGateway/SecureApiGateway/issues/876
=> 876: Disable message capturing for IDMClientHandler to stop messages being captured twice

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/ApiClient.java
jwks field is allowed to be null, therefore NPE is being thrown when .toJsonValue() is called on it.
Changing ApiClient.toString impl to let the JVM call toString on the individual fields to avoid NPEs. The JWKSet.toString is dumping the output as json.
https://github.com/SecureApiGateway/SecureApiGateway/issues/878
=> 878: Fixing ApiClient.toString NPE

config/7.1.0/securebanking/ig/config/prod/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/71-ob-jwkms-apiclient-issuecert.json, config/7.1.0/securebanking/ig/routes/routes-service/72-ob-jwkms-apiclient-getssa.json, config/7.1.0/securebanking/ig/routes/routes-service/73-ob-jwkms-apiclient-signclaims.json, config/7.1.0/securebanking/ig/routes/routes-service/74-ob-jwkms-apiclient-get-tls-cert.json, config/7.1.0/securebanking/ig/routes/routes-service/75-ob-jwkms-test-directory-jwks.json
Allow IG_TEST_DIRECTORY_ENABLED env var to configure this feature in production images. This allows us to run a production image in our development environments with this feature enabled.
By default, this feature is turned off.
Adding check to see if the feature is enabled as part of the jwkms routes which form part of the Test Trusted Directory functionality. Currently, the feature check is only done in the DCR route which prevents someone from using data issued by the directory.
https://github.com/SecureApiGateway/SecureApiGateway/issues/879
=> 879: Using IG_TEST_DIRECTORY_ENABLED config in production

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/config/prod/config/config.json
The `x-ob-url` header is used to build links in Open Banking responses for the Accounts APIs, the header is currently being set incorrectly by IG.
Changes implemented:
- Clearing any x-ob-url header sent from the client
- Setting x-ob-url to use the mtls domain
This will fix the self links built by the RS for APIs that use the `x-ob-url` header. Other APIs, such as Payments, need further investigation.
https://github.com/SecureApiGateway/SecureApiGateway/issues/874
=> 874: Fixing x-ob-url header passed downstream to use mtls domain

config/7.1.0/securebanking/ig/routes/routes-service/01-ob-rs-metadata.json, config/7.1.0/securebanking/ig/routes/routes-service/11-ob-account-access.json, config/7.1.0/securebanking/ig/routes/routes-service/12-ob-account-access-multiple-routes.json, config/7.1.0/securebanking/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/33-ob-domestic-payments-access.json, config/7.1.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/37-ob-scheduled-domestic-payments-access.json, config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/42-ob-domestic-standing-orders-access.json, config/7.1.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/47-ob-international-payment-access.json, config/7.1.0/securebanking/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json, config/7.1.0/securebanking/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/57-ob-international-standing-orders-access.json, config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/61-ob-file-payment-access.json, config/7.1.0/securebanking/ig/routes/routes-service/63-ob-domestic-vrp-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/65-ob-domestic-vrps-access.json, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRs.groovy
X-Forwarded-Prefix is used to contain a baseUri that exists on the gateway/ingress that has been removed when calling the upstream service (RS).
This fixes an issue with the Payments API links being generated by the RS being incorrect (missing the /rs path prefix). Spring HATEOAS impl uses the X-Forwarded-Host and X-Forwarded-Prefix headers when building a self link.
This change removes the needs to add the prefix in manually as part of the RS discovery response post-processing, which cleans up the ProcessRs script and route.
https://github.com/SecureApiGateway/SecureApiGateway/issues/874
=> 874: Adding X-Forwarded-Prefix header to RS RP requests

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/mtls/FromHeaderCertificateRetriever.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/mtls/TokenEndpointTransportCertValidationFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/mtls/TransportCertValidationFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/mtls/FromHeaderCertificateRetrieverTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/mtls/TokenEndpointTransportCertValidationFilterTest.java
When mTLS cert validation is done as part of the token_endpoint AS route, then error responses need to conform to the OAuth 2.0 spec. https://www.rfc-editor.org/rfc/rfc6749#section-5.2
Adding an errorResponse method to TokenEndpointTransportCertValidationFilter which produces errors in the correct format. Example response:
```
HTTP 401 UNAUTHORIZED
{
"error":"invalid_client",
"error_description":"Client mTLS certificate not provided"
}
```
The TransportCertValidationFilter is used on Open Banking routes, it needs to produce an error that conforms to the OB spec and and therefore has not been updated.
https://github.com/SecureApiGateway/SecureApiGateway/issues/916
=> 916: Fixing TokenEndpointTransportCertValidationFilter error responses

config/7.1.0/securebanking/ig/config/dev/config/admin.json, config/7.1.0/securebanking/ig/config/prod/config/admin.json
The connector configuration in admin.json configures the HTTP Server settings for IG.
Adding this configuration and increasing the maxInitialLineLength from the default 4k to 8k to fix an issue with long request URIs resulting in a HTTP 414 error.
Setting maxHeaderSize to 16k to match the value used in http client configuration in config.json
https://github.com/SecureApiGateway/SecureApiGateway/issues/917
=> 917: Configuring server connector in order to fix a HTTP 414 error

config/7.1.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/SoftwareStatement.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectory.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryOpenBankingTest.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectorySecureApiGateway.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/models/SoftwareStatementBuilderTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/models/SoftwareStatementTestFactory.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryOpenBankingTestTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryServiceStaticTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryTestFactory.java
Adding support for clientName claim in the TrustedDirectory configuration, using this to extract the clientName from the software statement during DCR. Using the value extracted to set the IDM ApiClient.name field.
https://github.com/SecureApiGateway/SecureApiGateway/issues/883
=> 883: Configuring ApiClient.name to be equal to a value from the software statement

.github/workflows/merge.yml, .github/workflows/pr.yml, .github/workflows/release-publish-java.yml, .github/workflows/release.yml, .github/workflows/slackNotification.yml, Makefile, pom.xml
Changes to make ready build and publish `IG` java extensions and docker image.
> To build the java artifact is necessary a specific maven settings to download the dependencies from the protected repository, so that it is not possible call the reusable workflow `release-publish-java` from gateway-parent.
- Updated make file, now if env is not provided we assumed 'prod' as environment to build the docker image
- Updated merge master workflow
- Updated PR workflow
- Created local `release-publish-java` workflow to setup properly the maven setting to retrieve the dependencies from protected repository.
- Created release workflow, to build the java artifact is necessary use the local `release-publish-java` workflow
```yaml
release_java:
name: Call publish java
needs: [ release_prepare ]
uses: …
```
=> 812: release action

.github/workflows/release-prepare.yml, .github/workflows/release.yml
We can't use the reusable release prepare workflow from parent because doesn't have the proper maven settings to get the dependencies from a protected repository.
- Added release prepare workflow as local workflow
- Update release workflow to use local release prepare workflow
Issue: https://github.com/secureapigateway/secureapigateway/issues/812
=> 812: release action release prepare local workflow

config/7.1.0/securebanking/ig/routes/routes-service/74-ob-jwkms-apiclient-get-tls-cert.json, config/7.1.0/securebanking/ig/routes/routes-service/75-ob-jwkms-apiclient-get-signing-cert.json, config/7.1.0/securebanking/ig/routes/routes-service/76-ob-jwkms-test-directory-jwks.json, config/7.1.0/securebanking/ig/scripts/groovy/JwkmsGetTlsCert.groovy, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
There is a convenience method to allow clients to obtain the tls key/pem pair from the jwks issued by IG. There needs to be one for the sig key/pem pair too, then clients can easily obtain the key to use for signing
Issue: https://github.com/secureapigateway/secureapigateway/issues/945
=> 945: Add route to return key/pem for signing cert

config/7.1.0/securebanking/ig/scripts/groovy/RepoConsent.groovy
Currently to store the account to perform a payment we use the field defined as `debtorAccount`.
Spec validation rule: The PISP must ensure that the Initiation and Risk sections of the international-payment match the corresponding Initiation and Risk sections of the international-payment-consent resource. If the two do not match, the ASPSP must not process the request and must respond with a 400 (Bad Request)
The `debtorAccount` field is patched when the psu submit the consent decision, in consequence when the TPP submit a payment, and the system validates the initiation object from payment request against the initiation object from the consent, the validation fails because the initiation objects do not match because the consent has been modified by the system.
We need to skip update the …
=> 947: Validation of initiation object, skip patch the debtor account and update accountId when debtor account is null

config/7.1.0/securebanking/ig/config/dev/config/config.json, config/7.1.0/securebanking/ig/config/prod/config/config.json, config/7.1.0/securebanking/ig/routes/routes-service/72-ob-jwkms-apiclient-getssa.json, config/7.1.0/securebanking/ig/routes/routes-service/76-ob-jwkms-test-directory-jwks.json
The `TestDirectorySigningKeyStore` object is currently defined in config.json's heap and referenced by the routes that use it. This means that all configuration properties needed to configure this object must be supplied in order for IG to start. 
Therefore, even if we remove the Test Directory routes this [config](https://github.com/SecureApiGateway/SecureApiGateway/wiki/Configuring-Trusted-Directories#configuring-test-trusted-directory) is still needed. The config is complex and shouldn't be required if a deployment never wishes to use the functionality.
In this change we are moving`TestDirectorySigningKeyStore` into the heap of the routes that use it. This means that if we omit the Test Directory configuration properties then only those routes are broken, all other gateway …
=> 978: Allow Test Directory to be disabled by removing its configuration properties

config/7.1.0/securebanking/ig/routes/routes-service/11-ob-account-access.json, config/7.1.0/securebanking/ig/routes/routes-service/12-ob-account-access-multiple-routes.json, config/7.1.0/securebanking/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/63-ob-domestic-vrp-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json, config/7.1.0/securebanking/ig/scripts/groovy/ConsentIdValidator.groovy, config/7.1.0/securebanking/ig/scripts/groovy/SaveIntentIdOnAttributesContext.groovy
Issue: https://github.com/secureapigateway/secureapigateway/issues/979
Added a new validation script on the payment submit routes.
This script is comparing the consentId from the request payload versus the consentId from the provided access token. By doing this comparison, we prevent resources being submitted with a token obtained for another consent.
=> Adding crosscheck between request consentId vs token consentId

config/7.1.0/securebanking/ig/scripts/groovy/ObResponseCheck.groovy
For validation errors, the RS will return Error objects which include a path field. The path indicates which field within the request is invalid.
Adding logic to retain this field if it is present in the RS response.
There's a separate issue to review and rewrite the ObResponseCheck script, see: https://github.com/SecureApiGateway/SecureApiGateway/issues/872
https://github.com/SecureApiGateway/SecureApiGateway/issues/578
=> 578: Retain Path field in OB Errors object

docker/7.1.0/ig/Dockerfile
- Deleted apt-get commands from docker file to update the system and install nano and vim to avoid the bug [993755](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=993755) reported in debian
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1020
=> 1020: Fix docker build deleting apt-get commands

config/7.1.0/securebanking/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/31-ob-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/33-ob-domestic-payments-access.json
Updating Domestic Payment Consent route to reverse proxy RS.
Removing filters which impl IDM Consent logic in IG from Domestic Payment routes.
Removing AM policy script call from Domestic Payment routes, this is now implemented in the RS/RCS.
Adding `x-api-client-id` header to all Domestic Payment API calls.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1012
=> 1012: Domestic Payment Consent route to call RS

config/7.1.0/securebanking/ig/routes/routes-service/10-ob-account-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/11-ob-account-access.json, config/7.1.0/securebanking/ig/routes/routes-service/12-ob-account-access-multiple-routes.json
- 10-ob-account-consent.json now reverse proxies the RS which implements the Account Access Consents API
- Routes using the consent to access data now no longer call the policy in AM, instead the RS/RCS will enforce this
- These routes also supply a new header `x-intent-id` which communicates the `openbanking_intent_id` from the access_token
- All routes now supply the `x-api-client-id` header
https://github.com/SecureApiGateway/SecureApiGateway/issues/1035
=> 1035: Updating Accounts Access routes to support Mongo Consent Store

config/7.1.0/securebanking/ig/routes/routes-service/35-ob-scheduled-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/37-ob-scheduled-domestic-payments-access.json
https://github.com/SecureApiGateway/SecureApiGateway/issues/1060
=> 1060: Updating Domestic Scheduled Payment routes to use the RS Consent API

config/7.1.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/42-ob-domestic-standing-orders-access.json
https://github.com/SecureApiGateway/SecureApiGateway/issues/1061
=> 1061: Updating Domestic Standing Order routes to use the RS Consent API

config/7.1.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/59-ob-file-payment-consent-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/61-ob-file-payment-access.json, config/7.1.0/securebanking/ig/scripts/groovy/ProcessRs.groovy
Removing `GetFilePaymentFile` and `CreateFilePaymentFile` links from the ProcessRs script, as the RS is now setting these automatically.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1065
=> 1065: Updating File Payment routes to use the RS Consent API

config/7.1.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/47-ob-international-payment-access.json, config/7.1.0/securebanking/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json
https://github.com/SecureApiGateway/SecureApiGateway/issues/1062
=> 1062: Updating International Payment routes to work with RS Consent API

config/7.1.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json, config/7.1.0/securebanking/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json
https://github.com/SecureApiGateway/SecureApiGateway/issues/1063
=> 1063: Updating International Scheduled Payment routes to work with RS Consent API

config/7.1.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json, config/7.1.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/57-ob-international-standing-orders-access.json
https://github.com/SecureApiGateway/SecureApiGateway/issues/1064
=> 1064: Updating International Standing Order routes to work with RS Consent API

config/7.1.0/securebanking/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json, config/7.1.0/securebanking/ig/routes/routes-service/63-ob-domestic-vrp-funds-confirmation.json, config/7.1.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json, config/7.1.0/securebanking/ig/scripts/groovy/RequestEntityConsentIdValidator.groovy, config/7.1.0/securebanking/ig/scripts/groovy/RequestPathConsentIdValidator.groovy
RequestEntityRequestEntityConsentIdValidator (previously called: ConsentIdValidator) ensures that VRP funds confirmation POST request entities have a consentId matching the consentId in the access_token.
New RequestPathConsentIdValidator added for non-VRP payment routes to apply the same validation logic to the consentId in the request URI.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1052
=> 1052: Validating Funds Confirmation Request ConsentId is valid for the access_token

pom.xml, secure-api-gateway-ig-extensions/pom.xml
- Upgrade maven artifact to version 2.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1099
=> 1099: upgrade maven artifact to version 2.0.0

config/7.2.0/securebanking/ig/routes/routes-service/10-ob-account-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/11-ob-account-access.json, config/7.2.0/securebanking/ig/routes/routes-service/12-ob-account-access-multiple-routes.json, config/7.2.0/securebanking/ig/routes/routes-service/30-ob-payment-consent-funds-confirmation.json, config/7.2.0/securebanking/ig/routes/routes-service/31-ob-payment-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json, config/7.2.0/securebanking/ig/routes/routes-service/35-ob-scheduled-payment-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.2.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json, config/7.2.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.2.0/securebanking/ig/routes/routes-service/48-ob-international-payment-funds-confirmation.json, config/7.2.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json, config/7.2.0/securebanking/ig/routes/routes-service/53-ob-international-scheduled-payment-funds-confirmation.json, config/7.2.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json, config/7.2.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json, config/7.2.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/63-ob-domestic-vrp-funds-confirmation.json, config/7.2.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json, config/7.2.0/securebanking/ig/routes/routes-service/66-ob-funds-confirmation-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/67-ob-funds-confirmation-availability.json, config/7.2.0/securebanking/ig/scripts/groovy/AuditConsent.groovy
consentIdLocator has been updated to locate the ConsentId in the OB API response, rather than the IDM Consent Store response
Fixing issue when Consent is deleted, the consentIdLocator does not work for this use case currently.
Example audit log:
```
{
"_id": "cf748620-f908-496b-ad90-396d5eecba48-345",
"timestamp": 1692269591646,
"eventName": "OB-CONSENT-CREATE",
"transactionId": "b485cfdd-d83b-46c2-b4be-0d0fb84ca79c",
"consent": {
"id": "AAC_79aa744b-8fec-47a2-8e45-41a7cbf49534",
"role": "AISP"
},
"fapiInfo": {
"x-fapi-interaction-id": "b485cfdd-d83b-46c2-b4be-0d0fb84ca79c"
},
"source": "audit",
"topic": "ObConsentTopic",
"level": "INFO"
}
```
https://github.com/SecureApiGateway/SecureApiGateway/issues/1108
=> 1108: Fixing consentIdLocator AuditConsent config

config/7.2.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json
Previously the TokenRequestHandler was being used, this uses the SettingNewEntity filter to change the client_credentials grant into a password grant and adds the username and password. This adds extra processing to the request chain, and is swapping the use of a stronger grant type for a weaker one with no added benefit. 
It is also quite confusing, as in the IG route it appears that we are going to get a client_credentials grant as we are using `ClientCredentialsOAuth2ClientFilter`
Password grant is being removed in OAuth2.1, therefore it should be avoided whenever possible.
Removing unnecessary scope: fr:idm:* from the gateway access_token request
https://github.com/SecureApiGateway/SecureApiGateway/issues/1120
=> 1120: Switching to use the ForgeRockClientHandler in the DCR AddIgAccessTokenForNewRegistrations filter

config/7.2.0/securebanking/ig/config/dev/config/config.json, config/7.2.0/securebanking/ig/config/prod/config/config.json, config/7.2.0/securebanking/ig/routes/routes-service/10-ob-account-consent.json, config/7.2.0/securebanking/ig/routes/routes-service/54-ob-token-endpoint.json, config/7.2.0/securebanking/ig/scripts/groovy/SetIdmPasswordGrantCredentials.groovy
TokenRequestHandler is only needed by the IDMClientHandler. Moving it as an inline handler definition so that it cannot be used elsewhere. IDM does not appear to support client_credentials access_tokens OOTB, hence why we use the password grant with a special IG IDM user identity.
Renaming SettingNewEntity => SetIdmPasswordGrantCredentials to make it clearer what the script does.
Changing the gateway token request from the token endpoint route to use the ForgeRockClientHandler, as it can use client_credentials flow.
Removing the gateway token request from the OB Account Access route as it is not needed. Only the client's access_token is needed, which the route is validating.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1121
=> 1121: Making use of TokenRequestHandler only in IDMClientHandler

.gitignore, config/7.2.0/securebanking/ig/routes/routes-service/200-events-admin-api.json, config/7.2.0/securebanking/ig/scripts/groovy/SignEventNotifications.groovy
To simulate events notifications in test facility bank this PR provides a new route to provide an endpoint where the TPP or ASPSP can import event notification messages. Event Notifications messages must be signed for non-repudiation, so that IG will sign the event SET's (Signed JWT) to be store in RS.
- Added new route 200-events-admin-api.json to intercept all request to admin event API '/rs/admin/data/events'
- Added script to sign the events from request to build the proper SET's (JWT signed) to simulate event notifications
- Updated .gitignore file to skip push the ig extensions java library
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/998
=> 998: route to import event messages to RS

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/am/ReSignIdTokenFilter.java
The callback `newSigningHandler` is used to produce the signed JWT, we are currently using `thenAsync` but this is unnecessary as the callback code does not need to make any subsequent async calls.
Fixing to use the `then` callback as it is simpler and more performant
https://github.com/SecureApiGateway/SecureApiGateway/issues/1138
=> 1138: Fixing ReSignIdTokenFilter newSigningHandler Promise to use `then` callback instead of `thenAysnc`

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/FAPIAdvancedDCRValidationFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/FAPIAdvancedDCRValidationFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/mtls/DefaultTransportCertValidatorTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/util/CryptoUtils.java
Calling X509Certificate.checkValidity() in FAPIAdvancedDCRValidaionFilter to check if the current date and time are within the validity period for the client's mTLS cert.
https://github.com/SecureApiGateway/SecureApiGateway/issues/862
=> 862: Adding certificate validity date check to FAPIAdvancedDCRValidaionFilter

config/7.3.0/securebanking/ig/config/dev/config/config.json, config/7.3.0/securebanking/ig/config/prod/config/config.json, config/7.3.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json, config/7.3.0/securebanking/ig/routes/routes-service/54-ob-token-endpoint.json
ClientCredentialsOAuth2ClientFilter configuration is using deprecated options, our configuration has been updated to use the endpointHandler as per the documentation: https://backstage.forgerock.com/docs/ig/2023.4/reference/Filters.html#ClientCredentialsOAuth2ClientFilter
https://github.com/SecureApiGateway/SecureApiGateway/issues/1163
=> 1163: Updating to use ClientCredentialsOAuth2ClientFilter endpointHandler configuration

config/7.3.0/securebanking/ig/scripts/groovy/CreateApiClient.groovy, config/7.3.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/SoftwareStatement.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectory.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryOpenBankingTest.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectorySecureApiGateway.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/models/SoftwareStatementBuilderTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/models/SoftwareStatementTestFactory.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryOpenBankingTestTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryServiceStaticTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/TrustedDirectoryTestFactory.java
Until now when a CDR is request, It was stored the `orgId` claim value from the Software Statement in the api client organisation name.
This is a fix to store the `org_name` claim value, retrieved from the Software Statement, in the api client organisation name instead of the `org_id` claim value.
- Added support to get the value from Software Statement `org_name` claim to be stored in IDM instead of orgId.
- Updated the trusted directories with a new property to retrieve and store the `org_name` claim value.
- Updated the current unit tests to cover the new `org_name` claim value retrieved from the Software Statement.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1162
=> 1162: store IDM orgName instead of orgId in api client org name

config/7.3.0/securebanking/ig/routes/routes-service/05-ob-as-token-endpoint.json, config/7.3.0/securebanking/ig/routes/routes-service/100-internal-repo.json, config/7.3.0/securebanking/ig/routes/routes-service/99-ob-as-passthrough.json
The name of the route is used for the routeId in metrics events, renaming the following routes to make the metrics reports easier to understand:
- 54-ob-token-endpoint.json => 05-ob-as-token-endpoint.json , renaming to follow the same pattern as the authorize endpoint
- 60-internal-repo.json => 100-internal-repo.json , renaming due to clash with ob route 60-ob-file-payment-submission
- 99-ob-as.json => 99-ob-as-passthrough.json to make it clearer that requests are simply passed through to the AS.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1151
=> 1151: Cleanup IG rotue names to make metrics reports clearer

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/RouteMetricsEvent.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/RouteMetricsFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/metrics/LoggerRouteMetricsEventPublisherTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/metrics/RouteMetricsFilterTest.java
The softwareId is the id of the Software Statement that the ApiClient has used to register.
Multiple OAuth2.0 registrations (and thus ApiClients) can be registered using he same Software Statement, storing the softwareId allows us to filter metrics for all ApiClients registered with a particular Software Statement.
This can be useful if we want to exclude all data produced by our automated tests.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1151
=> 1151: Adding softwareId field to RouteMetricsEvent

config/7.3.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
A bug was introduced in PR: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/449
As part of refactoring in this PR to make the ApiClient available for the RouteMetricsFilters, a bug was introduced in the DCR GET response. The software_statement field was missing due to the ApiClient in the attributes context having different fields names to the previous implementation.
Fixing ProcessRegistration to call the correct methods on ApiClient to obtain the software_statement.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1179
=> 1179: Setting software_statement correctly in DCR GET response

config/7.3.0/securebanking/ig/config/dev/config/config.json, config/7.3.0/securebanking/ig/config/prod/config/config.json
Adding support for new environment variable: `IG_OAUTH2_TOKEN_ENDPOINT_AUTH_METHODS`
This is expected to be a comma separated list of strings containing the OAuth2.0 token_endpoint_auth_methods supported by this deployment.
Defaulting to: `private_key_jwt,tls_client_auth`
https://github.com/SecureApiGateway/SecureApiGateway/issues/1189
=> 1189: Allow OAuth2.0 token_endpoint_auth_methods to be configured via environment variable

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/common/rest/HttpHeaderNames.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/idm/AuthorizeResponseFetchApiClientFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/authorize/BaseFapiAuthorizeRequestValidationFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/idm/BaseAuthorizeResponseFetchApiClientFilterTest.java
Using the OAuthErrorResponseFactory to create an invalid_request error when the client_id param is missing from requests processed by AuthorizeResponseFetchApiClientFilter.
HTTP 400 Bad Request is now returned with the following error message:
```
{
"error": "invalid_request",
"error_description": "'client_id' is missing in the request."
}
```
https://github.com/SecureApiGateway/SecureApiGateway/issues/1205
=> 1205: Improving AuthorizeResponseFetchApiClientFilter to return a properly formatted OAuth 2.0 error when client_id param is missing

config/7.3.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
"code" response_type is valid when doing JARM, allow registrations to specify this value so that JARM can be used when calling /authorize.
Clients are now able to register with any of the following combinations of response_type:
- ["code id_token"]
- ["code"]
- ["code id_token", "code"]
- Array order not important
https://github.com/SecureApiGateway/SecureApiGateway/issues/973
=> 973: Allow DCRs using "code" response_type to enable the use of JARM

config/7.3.0/securebanking/ig/routes/routes-service/04-ob-as-authorize.json, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/SecureApiGatewayClassAliasResolver.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/idm/AuthorizeResponseFetchApiClientFilterHeaplet.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/idm/AuthorizeResponseFetchApiClientFilterTest.java
The route protecting /authorize was failing to load due to a bug introduced by the PR https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/467 which extracted the AuthorizeResponseFetchApiClientFilterHeaplet class.
Fixing the issue by updating the SecureApiGatewayClassAliasResolver to reference the new class.
Correcting a typo in the filter name alias renaming Authorise => Authorize to match the OAuth2.0 terminology.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1215
=> 1215: Fixing AuthorizeResponseFetchApiClientFilter alias to reference the Heaplet correctly

config/7.3.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/FAPIAdvancedDCRValidationFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/authorize/BaseFapiAuthorizeRequestValidationFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/FAPIAdvancedDCRValidationFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/authorize/BaseFapiAuthorizeRequestValidationFilterTest.java
- DCR filter validates at FAPI compliant response_types are being registered ("code", "code id_token" or both)
- Logic to validate response_mode has been moved to the authorize filter as it is only specified in authorize requests
- Authorize checks that the chosen response_type for that particular call is being used in a FAPI compliant fashion
- For JARM the response_type = "code" then response_mode is validated to check that it is "jwt"
- For non-JARM the response_tyoe = "code id_token", the scope requested is validated to check that it includes "openid"
- Fixing bug in ProcessRegistration script preventing DCR registering multiple response_types
https://github.com/SecureApiGateway/SecureApiGateway/issues/1211
=> 1211: Fixing response_type validation for DCR and Authorize requests

.github/workflows/merge.yml, .github/workflows/pr.yml, .github/workflows/release-publish-java-and-docker.yml, .github/workflows/release.yml, Makefile
- Change any pipelines to push to the new Artifact Registry
- Change any pipelines / packages that pull images to use the new Artifact Registry
- Change Auth to GCP pipeline command to use V2 as V0 is deprecated
Issue:
- https://github.com/SecureApiGateway/SecureApiGateway/issues/987
- https://github.com/SecureApiGateway/SecureApiGateway/issues/1202
=> 987: Changes for migration to Artifact Registry

.github/workflows/pr.yml
The build jars during build maven step will now be included in the build docker image as they were being left out
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1217
=> 1217: Merge check and build step together

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/am/AuthorizeResponseJwtReSignFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/authorize/BaseFapiAuthorizeRequestValidationFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/am/AuthorizeResponseJwtReSignFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/authorize/BaseFapiAuthorizeRequestValidationFilterTest.java
Supporting all JARM response_mode values: "jwt", "query.jwt", "fragment.jwt", "form_post.jwt" in validation logic.
BaseFapiAuthorizeRequestValidationFilter now validates that one of the JARM response_mode values is specified when response_type is code (rather than only allowing response_mode="jwt").
AuthorizeResponseJwtReSignFilter handles JARM JWT re-signing in a similar fashion.
A separate issue has been raised to review how we handle form_post / form_post.jwt re-signing, as it is not currently supported by our system (the AM response with the invalidly signed JWTs will be passed through). See: https://github.com/SecureApiGateway/SecureApiGateway/issues/1233
https://github.com/SecureApiGateway/SecureApiGateway/issues/1222
=> 1222: Adding support for all jwt response_mode values in validation logic

.github/workflows/release-publish-java-and-docker.yml, .github/workflows/release.yml
Issue with workflows calling another workflow and secrets, seems that 'called' workflows cannot access the secrets, so the values have to be passed from the 'calling' workflow
When changing to artifact registry some of these values were changed causing errors 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/987
=> 987: Artifact Registry Migration

.github/workflows/release-publish-java-and-docker.yml, .github/workflows/release.yml, Makefile
I _think_ the issue is that we are passing a var as a secret and something is getting lost in translation, the GAR (Google artifact registry) is a variable in the organisation as it doesn't need to be kept secret, so changed the workflows to use it as a var(input) instead of a secret as we do when building PRs
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/987
=> 987: Try passing GAR var as variable instead of secret

.github/workflows/codeql.yml
Adding the credentials to access FR artifactory, required to be able to download the openig dependency used by this project.
https://github.com/SecureApiGateway/SecureApiGateway/issues/900
=> 900: Supplying maven credentials in CodeQL workflow

config/7.3.0/securebanking/ig/scripts/groovy/FapiTransactionIdFilter.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/FAPIUtils.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/RouteMetricsEvent.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/RouteMetricsFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/FAPIUtilsTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/metrics/LoggerRouteMetricsEventPublisherTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/metrics/RouteMetricsFilterTest.java
New field RouteMetricsEvent.fapiInteractionId has been added, which is set to the value of the x-fapi-interaction-id header.
This allows requests to be traced through the system based on metrics event data. This can be useful for investigating errors or high request latencies.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1273
=> 1273: Adding x-fapi-interaction-id to RouteMetricsEvent

.github/workflows/merge.yml
'gate' was still a part of the repo name in the tagging which is no longer required
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1276
=> 1276: Docker Tag not happening in IG

config/7.3.0/securebanking/ig/routes/routes-service/02-ob-as-metadata.json
The OIDC well-known response contains a jwks_uri entry specifying where the public certs for the TLS and signing certs used by the API provider can be found. We no longer need to override this as it is now configured in AM, in the OAuth2Provider's OIDC Advanced config.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1318
=> 1318: No longer overwrite jwks_uri in as well-known

config/7.3.0/securebanking/ig/scripts/groovy/ASWellKnownFilter.groovy
For now we can remove code relating to jwks_uri, although for non OB ecosystems it might be necessary to support this agian if it becomes difficult to add this to the AM config
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1318
=> 1318: Remove ability to override jwks_uri

.github/workflows/merge.yml, .github/workflows/pr.yml, .github/workflows/release-prepare.yml, .github/workflows/release-publish-java-and-docker.yml, README.md, config/7.3.0/securebanking/ig/config/dev/config/config.json, config/7.3.0/securebanking/ig/config/prod/config/config.json, config/7.3.0/securebanking/ig/routes/routes-service/72-ob-jwkms-apiclient-getssa.json, config/7.3.0/securebanking/ig/routes/routes-service/76-ob-jwkms-test-directory-jwks.json, config/7.3.0/securebanking/ig/routes/routes-service/80-jwks-proxy.json, pom.xml, secure-api-gateway-ob-uk-docker/Dockerfile
Upgrading IG to version 2024.3.0 (latest release).
See related core PR: https://github.com/SecureApiGateway/secure-api-gateway-core/pull/13
Minor change required to fix the JWKS proxy route used to call the OB directory JWKS endpoint. We now use the OBClientHandler and strip off all the request headers prior to calling the endpoint, this resolves an issue where OB directory infrastructure is failing to handle our request.
Updating KeyStoreSecretStore config to fix deprecation warnings.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1159
=> 1159: Upgrade IG to version 2024.3.0 

config/7.3.0/securebanking/ig/config/dev/config/config.json, config/7.3.0/securebanking/ig/config/prod/config/config.json, config/7.3.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json, config/7.3.0/securebanking/ig/routes/routes-service/80-jwks-proxy.json, config/7.3.0/securebanking/ig/scripts/groovy/JWKSProxyProcessRequest.groovy, config/7.3.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
This reverts commit 6da338bedf0b7c2773eca25c12ed39f3ba7213fc.
The jwksproxy route is needed for backward compatibility, existing OB deployments will have OAuth2.0 clients registered in AM with their jwks_uri configured via the proxy. Therefore, removing the route would break these existing clients.
The jwksproxy will be retained for OB deployments but will not be present in SAPI-G core.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1345
=> Revert "1345: Removing jwksproxy route (#529)"

config/7.3.0/securebanking/ig/config/dev/config/config.json, config/7.3.0/securebanking/ig/config/prod/config/config.json, config/7.3.0/securebanking/ig/routes/routes-service/31-ob-payment-consent.json, config/7.3.0/securebanking/ig/routes/routes-service/32-ob-payment-submission.json, config/7.3.0/securebanking/ig/routes/routes-service/35-ob-scheduled-payment-consent.json, config/7.3.0/securebanking/ig/routes/routes-service/36-ob-scheduled-payment-submission.json, config/7.3.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json, config/7.3.0/securebanking/ig/routes/routes-service/41-ob-domestic-standing-orders-submission.json, config/7.3.0/securebanking/ig/routes/routes-service/45-ob-international-payment-consent.json, config/7.3.0/securebanking/ig/routes/routes-service/46-ob-international-payment-submission.json, config/7.3.0/securebanking/ig/routes/routes-service/50-ob-international-scheduled-payment-consent.json, config/7.3.0/securebanking/ig/routes/routes-service/51-ob-international-scheduled-payment-submission.json, config/7.3.0/securebanking/ig/routes/routes-service/55-ob-international-standing-order-consent.json, config/7.3.0/securebanking/ig/routes/routes-service/56-ob-international-standing-orders-submission.json, config/7.3.0/securebanking/ig/routes/routes-service/58-ob-file-payment-consent.json, config/7.3.0/securebanking/ig/routes/routes-service/59-ob-file-payment-consent-submission.json, config/7.3.0/securebanking/ig/routes/routes-service/60-ob-file-payment-submission.json, config/7.3.0/securebanking/ig/routes/routes-service/62-ob-domestic-vrp-consent.json, config/7.3.0/securebanking/ig/routes/routes-service/64-ob-domestic-vrps-submission.json, config/7.3.0/securebanking/ig/routes/routes-service/81-rcs-ui.json, config/7.3.0/securebanking/ig/routes/routes-service/83-rcs-api.json, config/7.3.0/securebanking/ig/scripts/groovy/ProcessDetachedSig.groovy
New config: jwtValidation.clockSkewAllowanceDuration (type [duration](https://backstage.forgerock.com/docs/ig/2024.3/reference/preface.html#definition-duration)) can be used to control the allowed clock skew, currently set as 5s
Configuring IdTokenValidationFilter's skewAllowance (used in RCS routes) to allow for a clock skew.
Updated ProcessDetachedSig.groovy to validate http://openbanking.org.uk/iat using the clock skew allowance supplied from config.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1358
=> 1358: Support configrable clock skew when validating iat

config/7.3.0/securebanking/ig/config/dev/config/config.json, config/7.3.0/securebanking/ig/config/prod/config/config.json
Removing the optional version configuration of AmService, using the AM version discovery functionality in IG.
This avoid having a misconfiguration when the AM version is upgraded / is different in different environments.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1377
=> 1377: Use version discovery functionality of AmService

config/7.3.0/securebanking/ig/routes/routes-service/33-ob-domestic-payments-access.json, config/7.3.0/securebanking/ig/routes/routes-service/37-ob-scheduled-domestic-payments-access.json, config/7.3.0/securebanking/ig/routes/routes-service/40-ob-domestic-standing-order-consent.json, config/7.3.0/securebanking/ig/routes/routes-service/42-ob-domestic-standing-orders-access.json, config/7.3.0/securebanking/ig/routes/routes-service/47-ob-international-payment-access.json, config/7.3.0/securebanking/ig/routes/routes-service/52-ob-international-scheduled-payment-access.json, config/7.3.0/securebanking/ig/routes/routes-service/57-ob-international-standing-orders-access.json, config/7.3.0/securebanking/ig/routes/routes-service/61-ob-file-payment-access.json, config/7.3.0/securebanking/ig/routes/routes-service/65-ob-domestic-vrps-access.json
Where an endpoint only requires an access token obtained using a client_credentials grant, that access token should not require the openid scope
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1395
=> 1395: access token must not require openid scope

config/7.3.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy
softwareStatement.getJwksUri() has been changed to return a URI, updating ProcessRegistration.groovy to work with a URI.
Related core PR: https://github.com/SecureApiGateway/secure-api-gateway-core/pull/31
https://github.com/SecureApiGateway/SecureApiGateway/issues/1393
=> 1393: Updating ProcessRegistration to be compatible with core URI changes

.github/workflows/merge.yml
Correct componentName to be pushed to ci repo
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1389
=> 1389: Use CI Repo for standardised steps in github workflows

config/7.3.0/securebanking/ig/routes/routes-service/05-ob-as-token-endpoint.json, config/7.3.0/securebanking/ig/routes/routes-service/06-ob-as-par.json
ResponsePathTransportCertValidationFilter has been replaced with endpoint specific filters: TokenEndpointTransportCertValidationFilter and ParEndpointTransportCertValidationFilter.
Related core PR: https://github.com/SecureApiGateway/secure-api-gateway-core/pull/44
https://github.com/SecureApiGateway/SecureApiGateway/issues/1305
=> 1305: Fix route config

config/7.3.0/securebanking/ig/config/dev/config/config.json, config/7.3.0/securebanking/ig/config/prod/config/config.json, config/7.3.0/securebanking/ig/routes/routes-service/03-ob-dcr-register-tpp.json, config/7.3.0/securebanking/ig/routes/routes-service/05-ob-as-token-endpoint.json, config/7.3.0/securebanking/ig/routes/routes-service/06-ob-as-par.json
The StaticTrustedDirectoryService replaces TrustedDirectoriesService.
It includes configuration for the Open Banking and Secure API Gateway Test directories which have been migrated from code to config.
Related core PR: https://github.com/SecureApiGateway/secure-api-gateway-core/pull/40
https://github.com/SecureApiGateway/SecureApiGateway/issues/1413
=> 1413: Configure StaticTrustedDirectoryService

pom.xml, secure-api-gateway-ob-uk-docker/Dockerfile
docker image to `2026.4.0 `
core version to `3.0.1-SNAPSHOT`
parent version to `3.0.1-SNAPSHOT`
nimbus-jose version `9.40`
bouncy-castle version to `1.78.1`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1475
=> 1475: Upgrade openIG to 2024.6 ready for SAPIG 3.1.0

config/7.3.0/securebanking/ig/routes/routes-pod/99-kube-probe.json, config/7.3.0/securebanking/ig/routes/routes-service/999-ob-as-passthrough.json
Rename 99-as-passthrough.json to 999-platform-passthrough.json so that it is last in the route list. Update route name to reflect this.
The route is now responsible for passing any requests, which have not already been routed, through to the Identity Platform.
This includes AM endpoints such as the XUI and IDM endpoints to fetch config used to render the XUI.
Fix name of 98-kube-probe.json route for consistency.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1512
=> 1512: Make pass-through route send all traffic to Identity Platform

config/7.3.0/securebanking/ig/config/dev/config/admin.json, config/7.3.0/securebanking/ig/config/prod/config/admin.json
Deprecated option: maxHeaderSize replaced with maxTotalHeadersSize
Configuring the new option as 24KB, as the previous config allowed a max individual header size of 16KB, typically there is one large header (a JWT etc).
https://github.com/SecureApiGateway/SecureApiGateway/issues/1521
=> 1521: Update server side vertx max header config

config/7.3.0/securebanking/ig/scripts/groovy/ObResponseCheck.groovy
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1569
Added error code mappings in ObResponseCheck scripts - this is responsible of creating the OB compliant error responses that are thrown directly from IG.
=> Conversion of error codes and messages.

pom.xml
Bump Common to snapshot version 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1605
=> 1605: Make sure dev branches are not using latest snapshots for artifacts

pom.xml
- Revert Parent to `4.0.0` as no changes in repo to be released
- Bump Core to `4.0.4`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1642
=> 1642: Create SAPIG 4.0.4

pom.xml, secure-api-gateway-ob-uk-docker/7.3.0/ig/bin/import-pem-certs.sh, secure-api-gateway-ob-uk-docker/Dockerfile, secure-api-gateway-ob-uk-docker/pom.xml
Update Parent to 4.0.4-SNAPSHOT and run build-java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1654
=> 1654: Bump FAPI parent year and individual licenses

.github/workflows/pr.yml, pom.xml, secure-api-gateway-fapi-pep-rs-ob-docker/Dockerfile, secure-api-gateway-fapi-pep-rs-ob-docker/pom.xml, secure-api-gateway-ig-extensions-ob/pom.xml
Based off of V5.0.0
Updated version to 5.0.1-SNAPSHOT
Updated openIG version to 2025.6.2
Updated fapi-pep-as version to 5.0.1
Updated Dockerfile to gcr.io/forgerock-io/ig:2025.6.2-fapi
Issue: https://pingidentity.atlassian.net/browse/OPENIG-9573
=> OPENIG-9573: SAPIG 5.0.1 Release

pom.xml
Bump fapi-pep-as version to latest snapshot version
Issue: https://pingidentity.atlassian.net/jira/software/c/projects/OPENIG/boards/1322?selectedIssue=OPENIG-9633
=> OpenIG-9633: SAPIG 5.0.2 Release
